import { NextResponse } from 'next/server'

// The Model Intake operator credential is generated by scanner.sh into .env and
// handed to the API/worker containers. Before this route existed the UI simply
// asked the human to find that value and paste it in, which is friction with no
// security benefit on a single-operator local install: the token already lives
// in the browser session as soon as it is pasted, and every other ShakerScan API
// on a loopback bind is unauthenticated anyway.
//
// So the UI server hands the credential to its own same-origin page, but only
// when the deployment is actually bound to loopback. A remote/Tailscale/reverse
// -proxy deployment keeps the manual entry path, because there the browser is
// not necessarily the operator's own machine.
export const dynamic = 'force-dynamic'

const LOOPBACK_HOSTS = new Set(['', '127.0.0.1', 'localhost', '::1', '[::1]'])

function autofillDisabled(): boolean {
  const flag = (process.env.SHAKERSCAN_UI_OPERATOR_AUTOFILL || '').trim().toLowerCase()
  return flag === '0' || flag === 'false' || flag === 'no'
}

function deploymentIsLoopbackBound(): boolean {
  const bind = (process.env.SHAKERSCAN_BIND_HOST || '').trim().toLowerCase()
  return LOOPBACK_HOSTS.has(bind)
}

function normalizeHop(value: string): string {
  // IPv4-mapped IPv6 (::ffff:127.0.0.1) still denotes the local machine.
  return value.trim().toLowerCase().replace(/^::ffff:/, '')
}

function requestIsLoopback(request: Request): boolean {
  // A cross-origin page cannot read this response, but a reverse proxy in front
  // of the UI could still forward a remote browser here. Require the request to
  // look like it came from the local machine as well.
  const host = (request.headers.get('host') || '').replace(/:\d+$/, '').toLowerCase()
  if (!LOOPBACK_HOSTS.has(host)) return false
  // Next populates x-forwarded-for on every request, so its presence proves
  // nothing. What matters is that no hop in the chain is remote.
  const forwarded = request.headers.get('x-forwarded-for')
  if (!forwarded) return true
  return forwarded.split(',').every((hop) => LOOPBACK_HOSTS.has(normalizeHop(hop)))
}

export async function GET(request: Request) {
  const token = (process.env.MODEL_INTAKE_OPERATOR_TOKEN || '').trim()

  if (autofillDisabled()) {
    return NextResponse.json(
      { available: false, reason: 'disabled', detail: 'Operator credential autofill is disabled for this deployment.' },
      { headers: { 'Cache-Control': 'no-store' } }
    )
  }
  if (!deploymentIsLoopbackBound() || !requestIsLoopback(request)) {
    return NextResponse.json(
      {
        available: false,
        reason: 'remote_deployment',
        detail:
          'This deployment is not bound to loopback. Paste the MODEL_INTAKE_OPERATOR_TOKEN value from the server .env, or configure MODEL_INTAKE_OPERATOR_CREDENTIALS_JSON for per-reviewer identities.',
      },
      { headers: { 'Cache-Control': 'no-store' } }
    )
  }
  if (token.length < 32) {
    return NextResponse.json(
      {
        available: false,
        reason: 'not_configured',
        detail:
          'No Model Intake operator credential is configured. Run ./scanner.sh start to generate one, then restart the UI container.',
      },
      { headers: { 'Cache-Control': 'no-store' } }
    )
  }

  return NextResponse.json(
    { available: true, reason: 'local_deployment', token },
    { headers: { 'Cache-Control': 'no-store' } }
  )
}
