import { NextResponse } from 'next/server'

// The Model Intake operator credential is generated by scanner.sh into .env and
// handed to the API/worker containers. Before this route existed the UI simply
// asked the human to find that value and paste it in, which is friction with no
// security benefit on a single-operator local install: the token already lives
// in the browser session as soon as it is pasted, and every other ShakerScan API
// on a loopback bind is unauthenticated anyway.
//
// So the UI server hands the credential to its own same-origin page, but only
// when the deployment is actually bound to loopback. A remote/Tailscale/reverse
// -proxy deployment keeps the manual entry path, because there the browser is
// not necessarily the operator's own machine.
export const dynamic = 'force-dynamic'

const LOOPBACK_HOSTS = new Set(['', '127.0.0.1', 'localhost', '::1', '[::1]'])

function autofillDisabled(): boolean {
  const flag = (process.env.SHAKERSCAN_UI_OPERATOR_AUTOFILL || '').trim().toLowerCase()
  return flag === '0' || flag === 'false' || flag === 'no'
}

// The authoritative gate. Compose publishes the UI port on SHAKERSCAN_BIND_HOST
// (defaulting to 127.0.0.1), so a loopback value means the only machine that can
// open this page at all is the one running the deployment.
function deploymentIsLoopbackBound(): boolean {
  const bind = (process.env.SHAKERSCAN_BIND_HOST || '').trim().toLowerCase()
  return LOOPBACK_HOSTS.has(bind)
}

function requestLooksLocal(request: Request): boolean {
  // Deliberately only the Host header. The UI runs inside a container, so the
  // peer address of a published-port request is Docker's bridge gateway
  // (172.x.x.x) and x-forwarded-for never contains a loopback hop — requiring
  // one disabled autofill on every containerized deployment, which is all of
  // them. The port binding above is what actually constrains who can connect;
  // this check only catches a reverse proxy serving the UI under a public name.
  const host = (request.headers.get('host') || '').replace(/:\d+$/, '').toLowerCase()
  return LOOPBACK_HOSTS.has(host)
}

function decline(reason: string, detail: string, hint: string) {
  return NextResponse.json(
    { available: false, reason, detail, hint },
    { headers: { 'Cache-Control': 'no-store' } }
  )
}

export async function GET(request: Request) {
  const token = (process.env.MODEL_INTAKE_OPERATOR_TOKEN || '').trim()

  // `detail` states what is affected in product terms; `hint` carries the
  // operations instruction. Leading with an environment variable name is the
  // wrong altitude for someone who just wants to scan a model.
  if (autofillDisabled()) {
    return decline(
      'disabled',
      'This deployment requires an operator credential to be entered by hand.',
      'Unset SHAKERSCAN_UI_OPERATOR_AUTOFILL on the UI service to let the deployment supply it.'
    )
  }
  if (!deploymentIsLoopbackBound() || !requestLooksLocal(request)) {
    return decline(
      'remote_deployment',
      'This deployment is reachable beyond the local machine, so corporate admission actions need an operator credential.',
      'Paste the MODEL_INTAKE_OPERATOR_TOKEN value from the server .env, or configure MODEL_INTAKE_OPERATOR_CREDENTIALS_JSON for per-reviewer identities.'
    )
  }
  if (token.length < 32) {
    return decline(
      'not_configured',
      'No operator credential is configured for this deployment yet.',
      'Run ./scanner.sh start to generate one, then recreate the UI container so it picks the value up.'
    )
  }

  return NextResponse.json(
    { available: true, reason: 'local_deployment', token },
    { headers: { 'Cache-Control': 'no-store' } }
  )
}
