// Generated by scripts/generate_hunt_contract.py. Do not edit by hand.

export const HUNT_START_CONTRACT = {
  "budget_dimensions": [
    {
      "label": "Maximum approval-gated actions",
      "minimum": 0,
      "name": "max_active_actions",
      "zeroable": true
    },
    {
      "label": "Maximum browser actions",
      "minimum": 0,
      "name": "max_browser_actions",
      "zeroable": true
    },
    {
      "label": "Maximum candidates",
      "minimum": 1,
      "name": "max_candidates",
      "zeroable": false
    },
    {
      "label": "Maximum capability calls",
      "minimum": 1,
      "name": "max_capability_calls",
      "zeroable": false
    },
    {
      "label": "Maximum device fragility points",
      "minimum": 0,
      "name": "max_device_fragility_points",
      "zeroable": true
    },
    {
      "label": "Maximum duration (seconds)",
      "minimum": 1,
      "name": "max_duration_seconds",
      "zeroable": false
    },
    {
      "label": "Maximum hosts",
      "minimum": 0,
      "name": "max_hosts",
      "zeroable": true
    },
    {
      "label": "Maximum HTTP requests",
      "minimum": 1,
      "name": "max_http_requests",
      "zeroable": false
    },
    {
      "label": "Maximum out-of-band interactions",
      "minimum": 0,
      "name": "max_oob_interactions",
      "zeroable": true
    },
    {
      "label": "Maximum state-changing requests",
      "minimum": 0,
      "name": "max_state_changing_requests",
      "zeroable": true
    },
    {
      "label": "Maximum TCP ports",
      "minimum": 0,
      "name": "max_tcp_ports",
      "zeroable": true
    },
    {
      "label": "Maximum UDP ports",
      "minimum": 0,
      "name": "max_udp_ports",
      "zeroable": true
    },
    {
      "label": "Maximum deterministic verifications",
      "minimum": 1,
      "name": "max_verifications",
      "zeroable": false
    }
  ],
  "budget_profiles": {
    "balanced": {
      "max_active_actions": 20,
      "max_browser_actions": 200,
      "max_candidates": 100,
      "max_capability_calls": 80,
      "max_device_fragility_points": 100,
      "max_duration_seconds": 3600,
      "max_hosts": 500,
      "max_http_requests": 5000,
      "max_oob_interactions": 50,
      "max_state_changing_requests": 20,
      "max_tcp_ports": 1200,
      "max_udp_ports": 1000,
      "max_verifications": 20
    },
    "fast": {
      "max_active_actions": 4,
      "max_browser_actions": 20,
      "max_candidates": 20,
      "max_capability_calls": 20,
      "max_device_fragility_points": 20,
      "max_duration_seconds": 900,
      "max_hosts": 50,
      "max_http_requests": 500,
      "max_oob_interactions": 10,
      "max_state_changing_requests": 4,
      "max_tcp_ports": 100,
      "max_udp_ports": 100,
      "max_verifications": 4
    },
    "thorough": {
      "max_active_actions": 80,
      "max_browser_actions": 1000,
      "max_candidates": 500,
      "max_capability_calls": 300,
      "max_device_fragility_points": 500,
      "max_duration_seconds": 14400,
      "max_hosts": 5000,
      "max_http_requests": 20000,
      "max_oob_interactions": 200,
      "max_state_changing_requests": 80,
      "max_tcp_ports": 10000,
      "max_udp_ports": 5000,
      "max_verifications": 100
    }
  },
  "budget_schema_version": "hunt-budget/v3",
  "credential_ref_fields": [
    "authorization_header_credential_id",
    "cookie_credential_id",
    "oauth_credential_profile_id",
    "primary_credential_profile_id",
    "secondary_credential_profile_id",
    "service_credential_profile_id",
    "ssh_credential_profile_id",
    "web_credential_profile_id"
  ],
  "limits": {
    "capabilities": 128,
    "credential_refs": 16,
    "goal_chars": 20000,
    "request_collections": 32,
    "skill_ids": 4
  },
  "patterns": {
    "capability": "^[a-z0-9][a-z0-9_.:-]{0,127}$",
    "identifier": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,255}$",
    "skill_id": "^skill\\.[a-z0-9][a-z0-9_.-]{0,127}$"
  },
  "policy_derived_zeros": {
    "mutation_disabled": [
      "max_state_changing_requests"
    ],
    "network_disabled": [
      "max_hosts",
      "max_tcp_ports",
      "max_udp_ports"
    ],
    "non_device_target": [
      "max_device_fragility_points"
    ],
    "oob_disabled": [
      "max_oob_interactions"
    ],
    "passive_without_credentials": [
      "max_active_actions"
    ]
  },
  "policy_fields": [
    "active_testing",
    "allow_identity_headers",
    "allow_oob_interactions",
    "allow_state_changing_http",
    "approval_receipt_id",
    "authorization_confirmed",
    "network_discovery",
    "scope_receipt_id"
  ],
  "schema_version": "hunt-start/v2",
  "skill_catalog": "/hunt/skills",
  "target_kinds": [
    "api",
    "device",
    "network",
    "web"
  ]
} as const

export const HUNT_BUDGET_PROFILES = HUNT_START_CONTRACT.budget_profiles
export const HUNT_BUDGET_DIMENSIONS = HUNT_START_CONTRACT.budget_dimensions
export const HUNT_ZEROABLE_BUDGET_DIMENSIONS = [
  "max_active_actions",
  "max_browser_actions",
  "max_device_fragility_points",
  "max_hosts",
  "max_oob_interactions",
  "max_state_changing_requests",
  "max_tcp_ports",
  "max_udp_ports"
] as const
export type HuntBudgetProfile = keyof typeof HUNT_BUDGET_PROFILES
export type HuntBudgetDimension = typeof HUNT_BUDGET_DIMENSIONS[number]['name']
export type HuntZeroableBudgetDimension = typeof HUNT_ZEROABLE_BUDGET_DIMENSIONS[number]
export type HuntTargetKind = typeof HUNT_START_CONTRACT.target_kinds[number]
