// Generated by scripts/generate_public_api_contract.py. Do not edit by hand.

export const PUBLIC_API_CONTRACT_SHA256 = "55b86ecaf10e557049f5273d62393ade1c3debb5adb88d3d8ea0877f05c92e76" as const

export const PUBLIC_API_OPERATIONS = {
  "list_credential_profiles_credential_profiles_get": { method: "GET", path: "/credential-profiles", surface: "credentials" },
  "create_credential_profile_credential_profiles_post": { method: "POST", path: "/credential-profiles", surface: "credentials" },
  "get_credential_profile_credential_profiles__profile_id__get": { method: "GET", path: "/credential-profiles/{profile_id}", surface: "credentials" },
  "patch_credential_profile_credential_profiles__profile_id__patch": { method: "PATCH", path: "/credential-profiles/{profile_id}", surface: "credentials" },
  "delete_credential_profile_credential_profiles__profile_id__delete": { method: "DELETE", path: "/credential-profiles/{profile_id}", surface: "credentials" },
  "rotate_credential_profile_credential_profiles__profile_id__rotate_post": { method: "POST", path: "/credential-profiles/{profile_id}/rotate", surface: "credentials" },
  "evidence_export_bundle_evidence_export_bundle_get": { method: "GET", path: "/evidence/export-bundle", surface: "evidence" },
  "evidence_export_manifest_evidence_export_manifest_get": { method: "GET", path: "/evidence/export-manifest", surface: "evidence" },
  "list_evidence_instances_evidence_instances_get": { method: "GET", path: "/evidence/instances", surface: "evidence" },
  "record_evidence_instance_evidence_instances_post": { method: "POST", path: "/evidence/instances", surface: "evidence" },
  "get_evidence_instance_evidence_instances__instance_id__get": { method: "GET", path: "/evidence/instances/{instance_id}", surface: "evidence" },
  "list_evidence_retention_executions_evidence_retention_executions_get": { method: "GET", path: "/evidence/retention/executions", surface: "evidence" },
  "evidence_retention_sweep_evidence_retention_sweep_post": { method: "POST", path: "/evidence/retention/sweep", surface: "evidence" },
  "get_evidence_object_evidence__evidence_id__get": { method: "GET", path: "/evidence/{evidence_id}", surface: "evidence" },
  "list_hunts_hunts_get": { method: "GET", path: "/hunts", surface: "hunt" },
  "start_hunt_hunts_post": { method: "POST", path: "/hunts", surface: "hunt" },
  "get_hunt_contract_hunts_contract_get": { method: "GET", path: "/hunts/contract", surface: "hunt" },
  "get_hunt_lifecycle_metrics_hunts_lifecycle_metrics_get": { method: "GET", path: "/hunts/lifecycle-metrics", surface: "hunt" },
  "get_hunt_hunts__hunt_id__get": { method: "GET", path: "/hunts/{hunt_id}", surface: "hunt" },
  "cancel_hunt_hunts__hunt_id__cancel_post": { method: "POST", path: "/hunts/{hunt_id}/cancel", surface: "hunt" },
  "create_hunt_candidate_hunts__hunt_id__candidates_post": { method: "POST", path: "/hunts/{hunt_id}/candidates", surface: "hunt" },
  "verify_hunt_candidate_hunts__hunt_id__candidates__candidate_id__verify_post": { method: "POST", path: "/hunts/{hunt_id}/candidates/{candidate_id}/verify", surface: "hunt" },
  "execute_hunt_capability_hunts__hunt_id__capabilities__capability_name__post": { method: "POST", path: "/hunts/{hunt_id}/capabilities/{capability_name}", surface: "hunt" },
  "finish_hunt_hunts__hunt_id__finish_post": { method: "POST", path: "/hunts/{hunt_id}/finish", surface: "hunt" },
  "export_hunt_transactions_hunts__hunt_id__http_transactions_get": { method: "GET", path: "/hunts/{hunt_id}/http-transactions", surface: "hunt" },
  "purge_hunt_transactions_hunts__hunt_id__http_transactions_delete": { method: "DELETE", path: "/hunts/{hunt_id}/http-transactions", surface: "hunt" },
  "query_hunt_hunts__hunt_id__query_post": { method: "POST", path: "/hunts/{hunt_id}/query", surface: "hunt" },
  "export_hunt_record_hunts__hunt_id__record_get": { method: "GET", path: "/hunts/{hunt_id}/record", surface: "hunt" },
  "resume_hunt_hunts__hunt_id__resume_post": { method: "POST", path: "/hunts/{hunt_id}/resume", surface: "hunt" },
  "confirm_hunt_shell_plan_hunts__hunt_id__shell_plans__plan_id__confirm_post": { method: "POST", path: "/hunts/{hunt_id}/shell-plans/{plan_id}/confirm", surface: "hunt" },
  "verify_model_intake_admission_model_intake_admission_verify_post": { method: "POST", path: "/model-intake/admission/verify", surface: "model_intake" },
  "list_model_intake_admissions_model_intake_admissions_get": { method: "GET", path: "/model-intake/admissions", surface: "model_intake" },
  "observe_model_intake_deployment_v2_model_intake_admissions_v2_observe_post": { method: "POST", path: "/model-intake/admissions/v2/observe", surface: "model_intake" },
  "verify_model_intake_admission_v2_model_intake_admissions_v2_verify_post": { method: "POST", path: "/model-intake/admissions/v2/verify", surface: "model_intake" },
  "get_model_intake_admission_model_intake_admissions__admission_id__get": { method: "GET", path: "/model-intake/admissions/{admission_id}", surface: "model_intake" },
  "revoke_model_intake_admission_model_intake_admissions__admission_id__revoke_post": { method: "POST", path: "/model-intake/admissions/{admission_id}/revoke", surface: "model_intake" },
  "get_model_intake_agent_session_model_intake_agent_session__session_id__get": { method: "GET", path: "/model-intake/agent/session/{session_id}", surface: "model_intake" },
  "cancel_model_intake_agent_session_model_intake_agent_session__session_id__cancel_post": { method: "POST", path: "/model-intake/agent/session/{session_id}/cancel", surface: "model_intake" },
  "reply_model_intake_agent_session_model_intake_agent_session__session_id__reply_post": { method: "POST", path: "/model-intake/agent/session/{session_id}/reply", surface: "model_intake" },
  "list_model_intake_automatic_reviews_model_intake_automatic_reviews_get": { method: "GET", path: "/model-intake/automatic-reviews", surface: "model_intake" },
  "create_model_intake_automatic_review_model_intake_automatic_reviews_post": { method: "POST", path: "/model-intake/automatic-reviews", surface: "model_intake" },
  "get_model_intake_automatic_review_model_intake_automatic_reviews__review_id__get": { method: "GET", path: "/model-intake/automatic-reviews/{review_id}", surface: "model_intake" },
  "get_model_intake_automatic_review_report_model_intake_automatic_reviews__review_id__report_get": { method: "GET", path: "/model-intake/automatic-reviews/{review_id}/report", surface: "model_intake" },
  "model_intake_capabilities_model_intake_capabilities_get": { method: "GET", path: "/model-intake/capabilities", surface: "model_intake" },
  "model_intake_check_catalog_model_intake_checks_get": { method: "GET", path: "/model-intake/checks", surface: "model_intake" },
  "resolve_model_intake_conversion_profile_model_intake_conversion_profiles_resolve_post": { method: "POST", path: "/model-intake/conversion-profiles/resolve", surface: "model_intake" },
  "resolve_model_intake_loader_profile_model_intake_loader_profiles_resolve_post": { method: "POST", path: "/model-intake/loader-profiles/resolve", surface: "model_intake" },
  "model_intake_operator_session_model_intake_operator_session_get": { method: "GET", path: "/model-intake/operator-session", surface: "model_intake" },
  "model_intake_provider_readiness_model_intake_providers_readiness_get": { method: "GET", path: "/model-intake/providers/readiness", surface: "model_intake" },
  "create_model_intake_reassessment_event_model_intake_reassessment_events_post": { method: "POST", path: "/model-intake/reassessment/events", surface: "model_intake" },
  "resolve_model_intake_model_intake_resolve_post": { method: "POST", path: "/model-intake/resolve", surface: "model_intake" },
  "cleanup_model_intake_quarantine_model_intake_retention_cleanup_post": { method: "POST", path: "/model-intake/retention/cleanup", surface: "model_intake" },
  "model_intake_runner_install_plan_model_intake_runners_install_plan_get": { method: "GET", path: "/model-intake/runners/install-plan", surface: "model_intake" },
  "model_intake_runner_readiness_model_intake_runners_readiness_get": { method: "GET", path: "/model-intake/runners/readiness", surface: "model_intake" },
  "model_intake_runner_stage_status_model_intake_runners_stage_get": { method: "GET", path: "/model-intake/runners/stage", surface: "model_intake" },
  "model_intake_runner_stage_model_intake_runners_stage_post": { method: "POST", path: "/model-intake/runners/stage", surface: "model_intake" },
  "model_intake_runner_storage_model_intake_runners_storage_get": { method: "GET", path: "/model-intake/runners/storage", surface: "model_intake" },
  "model_intake_runner_storage_cleanup_model_intake_runners_storage_cleanup_post": { method: "POST", path: "/model-intake/runners/storage/cleanup", surface: "model_intake" },
  "scan_model_intake_model_intake_scan_post": { method: "POST", path: "/model-intake/scan", surface: "model_intake" },
  "model_intake_scanner_readiness_model_intake_scanners_readiness_get": { method: "GET", path: "/model-intake/scanners/readiness", surface: "model_intake" },
  "get_model_intake_evidence_export_model_intake_scans__scan_id__evidence_export_get": { method: "GET", path: "/model-intake/scans/{scan_id}/evidence-export", surface: "model_intake" },
  "download_model_intake_license_bom_model_intake_scans__scan_id__license_bom_get": { method: "GET", path: "/model-intake/scans/{scan_id}/license-bom", surface: "model_intake" },
  "download_model_intake_sbom_model_intake_scans__scan_id__sbom_get": { method: "GET", path: "/model-intake/scans/{scan_id}/sbom", surface: "model_intake" },
  "model_intake_sbom_summary_model_intake_scans__scan_id__sbom_summary_get": { method: "GET", path: "/model-intake/scans/{scan_id}/sbom/summary", surface: "model_intake" },
  "download_model_intake_third_party_notices_model_intake_scans__scan_id__third_party_notices_get": { method: "GET", path: "/model-intake/scans/{scan_id}/third-party-notices", surface: "model_intake" },
  "list_model_intake_submissions_model_intake_submissions_get": { method: "GET", path: "/model-intake/submissions", surface: "model_intake" },
  "create_model_intake_submission_model_intake_submissions_post": { method: "POST", path: "/model-intake/submissions", surface: "model_intake" },
  "get_model_intake_submission_model_intake_submissions__submission_id__get": { method: "GET", path: "/model-intake/submissions/{submission_id}", surface: "model_intake" },
  "create_model_intake_agent_session_model_intake_submissions__submission_id__agent_session_post": { method: "POST", path: "/model-intake/submissions/{submission_id}/agent/session", surface: "model_intake" },
  "list_model_intake_agent_sessions_model_intake_submissions__submission_id__agent_sessions_get": { method: "GET", path: "/model-intake/submissions/{submission_id}/agent/sessions", surface: "model_intake" },
  "create_model_intake_approval_model_intake_submissions__submission_id__approvals_post": { method: "POST", path: "/model-intake/submissions/{submission_id}/approvals", surface: "model_intake" },
  "model_intake_embedding_configuration_model_intake_submissions__submission_id__embedding_configuration_get": { method: "GET", path: "/model-intake/submissions/{submission_id}/embedding-configuration", surface: "model_intake" },
  "attach_model_intake_runner_evidence_model_intake_submissions__submission_id__evidence_receipts_post": { method: "POST", path: "/model-intake/submissions/{submission_id}/evidence-receipts", surface: "model_intake" },
  "freeze_model_intake_evidence_model_intake_submissions__submission_id__freeze_evidence_post": { method: "POST", path: "/model-intake/submissions/{submission_id}/freeze-evidence", surface: "model_intake" },
  "create_model_intake_policy_decision_model_intake_submissions__submission_id__policy_decisions_post": { method: "POST", path: "/model-intake/submissions/{submission_id}/policy-decisions", surface: "model_intake" },
  "promote_model_intake_submission_model_intake_submissions__submission_id__promote_post": { method: "POST", path: "/model-intake/submissions/{submission_id}/promote", surface: "model_intake" },
  "get_model_intake_submission_report_model_intake_submissions__submission_id__report_get": { method: "GET", path: "/model-intake/submissions/{submission_id}/report", surface: "model_intake" },
  "model_intake_runner_bundle_model_intake_submissions__submission_id__runner_bundle_get": { method: "GET", path: "/model-intake/submissions/{submission_id}/runner-bundle", surface: "model_intake" },
  "list_model_intake_runner_jobs_model_intake_submissions__submission_id__runner_jobs_get": { method: "GET", path: "/model-intake/submissions/{submission_id}/runner-jobs", surface: "model_intake" },
  "create_model_intake_runner_job_model_intake_submissions__submission_id__runner_jobs_post": { method: "POST", path: "/model-intake/submissions/{submission_id}/runner-jobs", surface: "model_intake" },
  "refresh_model_intake_runner_job_model_intake_submissions__submission_id__runner_jobs__job_id__refresh_post": { method: "POST", path: "/model-intake/submissions/{submission_id}/runner-jobs/{job_id}/refresh", surface: "model_intake" },
  "attach_model_intake_static_run_model_intake_submissions__submission_id__static_runs_post": { method: "POST", path: "/model-intake/submissions/{submission_id}/static-runs", surface: "model_intake" },
  "rescan_model_intake_target_model_intake_targets__target_id__rescan_post": { method: "POST", path: "/model-intake/targets/{target_id}/rescan", surface: "model_intake" },
  "list_model_intake_trust_anchors_model_intake_trust_anchors_get": { method: "GET", path: "/model-intake/trust-anchors", surface: "model_intake" },
  "create_model_intake_trust_anchor_model_intake_trust_anchors_post": { method: "POST", path: "/model-intake/trust-anchors", surface: "model_intake" },
  "update_model_intake_trust_anchor_model_intake_trust_anchors__anchor_id__patch": { method: "PATCH", path: "/model-intake/trust-anchors/{anchor_id}", surface: "model_intake" },
  "deactivate_model_intake_trust_anchor_model_intake_trust_anchors__anchor_id__delete": { method: "DELETE", path: "/model-intake/trust-anchors/{anchor_id}", surface: "model_intake" },
  "list_request_collections_request_collections_get": { method: "GET", path: "/request-collections", surface: "collections" },
  "create_request_collection_request_collections_post": { method: "POST", path: "/request-collections", surface: "collections" },
  "get_request_collection_request_collections__collection_id__get": { method: "GET", path: "/request-collections/{collection_id}", surface: "collections" },
  "upsert_request_collection_binding_request_collections__collection_id__bindings_post": { method: "POST", path: "/request-collections/{collection_id}/bindings", surface: "collections" },
  "upsert_request_collection_environment_request_collections__collection_id__environments_post": { method: "POST", path: "/request-collections/{collection_id}/environments", surface: "collections" },
  "deactivate_request_collection_environment_request_collections__collection_id__environments__environment_id__delete": { method: "DELETE", path: "/request-collections/{collection_id}/environments/{environment_id}", surface: "collections" },
  "list_request_collection_requests_request_collections__collection_id__requests_get": { method: "GET", path: "/request-collections/{collection_id}/requests", surface: "collections" },
  "select_request_collection_index_request_collections__collection_id__select_post": { method: "POST", path: "/request-collections/{collection_id}/select", surface: "collections" },
  "upsert_request_collection_selection_request_collections__collection_id__selections_post": { method: "POST", path: "/request-collections/{collection_id}/selections", surface: "collections" },
  "deactivate_request_collection_selection_request_collections__collection_id__selections__selection_id__delete": { method: "DELETE", path: "/request-collections/{collection_id}/selections/{selection_id}", surface: "collections" },
  "get_scan_public_contract_scan_contracts_get": { method: "GET", path: "/scan/contracts", surface: "scan" },
  "preview_scan_contract_scan_contracts_preview_post": { method: "POST", path: "/scan/contracts/preview", surface: "scan" },
  "list_scans_scans_get": { method: "GET", path: "/scans", surface: "scan" },
  "submit_scan_scans_post": { method: "POST", path: "/scans", surface: "scan" },
  "submit_batch_scans_batch_post": { method: "POST", path: "/scans/batch", surface: "scan" },
  "get_scan_scans__scan_id__get": { method: "GET", path: "/scans/{scan_id}", surface: "scan" },
  "get_scan_actions_scans__scan_id__actions_get": { method: "GET", path: "/scans/{scan_id}/actions", surface: "scan" },
  "get_ai_redteam_report_scans__scan_id__ai_redteam_report_get": { method: "GET", path: "/scans/{scan_id}/ai-redteam-report", surface: "scan" },
  "list_scan_artifacts_scans__scan_id__artifacts_get": { method: "GET", path: "/scans/{scan_id}/artifacts", surface: "scan" },
  "download_scan_artifact_scans__scan_id__artifacts__artifact_id__get": { method: "GET", path: "/scans/{scan_id}/artifacts/{artifact_id}", surface: "scan" },
  "cancel_scan_scans__scan_id__cancel_post": { method: "POST", path: "/scans/{scan_id}/cancel", surface: "scan" },
  "get_scan_capabilities_scans__scan_id__capabilities_get": { method: "GET", path: "/scans/{scan_id}/capabilities", surface: "scan" },
  "get_scan_coverage_scans__scan_id__coverage_get": { method: "GET", path: "/scans/{scan_id}/coverage", surface: "scan" },
  "get_scan_deployment_decision_scans__scan_id__deployment_decision_get": { method: "GET", path: "/scans/{scan_id}/deployment-decision", surface: "scan" },
  "get_scan_device_activity_scans__scan_id__device_activity_get": { method: "GET", path: "/scans/{scan_id}/device-activity", surface: "scan" },
  "export_scan_transactions_scans__scan_id__http_transactions_get": { method: "GET", path: "/scans/{scan_id}/http-transactions", surface: "scan" },
  "purge_scan_transactions_scans__scan_id__http_transactions_delete": { method: "DELETE", path: "/scans/{scan_id}/http-transactions", surface: "scan" },
  "get_scan_logs_scans__scan_id__logs_get": { method: "GET", path: "/scans/{scan_id}/logs", surface: "scan" },
  "get_scan_parity_artifact_scans__scan_id__parity_artifact_get": { method: "GET", path: "/scans/{scan_id}/parity-artifact", surface: "scan" },
  "get_scan_queue_delivery_scans__scan_id__queue_delivery_get": { method: "GET", path: "/scans/{scan_id}/queue-delivery", surface: "scan" },
  "get_scan_result_scans__scan_id__result_get": { method: "GET", path: "/scans/{scan_id}/result", surface: "scan" },
} as const

export type CredentialProfileCreate = {
  target_kind: "web" | "api" | "network" | "device"
  target_id: string
  name: string
  auth_kind: "authorization_header" | "bearer_token" | "api_key_header" | "cookie" | "basic_auth" | "form_login" | "oauth_client_credentials" | "oauth_password" | "custom_headers" | "query_parameter" | "ssh_password" | "ssh_private_key" | "ssh_private_key_with_passphrase"
  principal_label?: string | null
  principal_slot?: "primary" | "secondary" | "service" | "ssh"
  secret?: string | null
  username?: string | null
  secondary_secret?: string | null
  header_name?: string | null
  endpoint_url?: string | null
  client_id?: string | null
  scopes?: Array<string>
  custom_headers?: Record<string, string> | null
  parameter_name?: string | null
  expires_at?: string | null
  allowed_capabilities?: Array<string>
  created_by?: string
}

export type CredentialProfilePatch = {
  expected_record_version: number
  name?: string | null
  principal_label?: string | null
  principal_slot?: "primary" | "secondary" | "service" | "ssh" | null
  expires_at?: string | null
  clear_expiry?: boolean
  is_active?: boolean | null
  allowed_capabilities?: Array<string> | null
}

export type CredentialProfileRotate = {
  expected_record_version: number
  secret?: string | null
  username?: string | null
  secondary_secret?: string | null
  header_name?: string | null
  endpoint_url?: string | null
  client_id?: string | null
  scopes?: Array<string>
  custom_headers?: Record<string, string> | null
  parameter_name?: string | null
  expires_at?: string | null
  clear_expiry?: boolean
  created_by?: string
}

export type DeviceAgentShellConfirmRequest = {
  plan_digest: string
  confirmation_phrase: string
  confirm_exact_commands?: boolean
  confirm_remote_device_effects?: boolean
}

export type EvidenceInstanceRequest = {
  finding_id?: string | null
  evidence_object_id?: string | null
  scan_id?: string | null
  target_id?: string | null
  concrete_url?: string | null
  object_id?: string | null
  payload_variant?: string | null
  request_response_refs?: Array<string>
  principal_pair?: Record<string, unknown>
  proof_observation?: Record<string, unknown>
  campaign_action_id?: string | null
  tool_receipt_id?: string | null
  redaction_profile?: string
  hash?: string | null
  retention_policy?: string
  proof_state?: string
  evidence_strength?: string | null
  metadata_json?: Record<string, unknown>
  created_by?: string | null
}

export type EvidenceRetentionSweepRequest = {
  dry_run?: boolean
  target_id?: string | null
  older_than_days?: number | null
  retention_class?: string | null
  limit?: number
  delete_local_files?: boolean
  approval_receipt_id?: string | null
  preview_id?: string | null
}

export type HuntCandidateRequest = {
  family: string
  locus?: Record<string, unknown>
  title: string
  claim: string
  severity?: "critical" | "high" | "medium" | "low" | "info"
  evidence_refs: Array<string>
  verifier_contract_id?: string | null
}

export type HuntCandidateVerifyRequest = {
  attempt?: number
}

export type HuntCapabilityRequest = {
  idempotency_key: string
  input?: Record<string, unknown>
}

export type HuntFinishRequest = {
  summary: string
  next_actions?: Array<string>
}

export type HuntQueryRequest = {
  kind?: "summary" | "endpoints" | "findings" | "principals" | "services" | "scans" | "collections" | "candidates" | "notes" | "receipts" | "hypotheses" | "graph_nodes" | "graph_edges"
  filter?: Record<string, unknown>
  limit?: number
}

export type HuntStartV2Response = ({
  hunt_id?: string | null
  target_kind?: string | null
  target_id?: string | null
  objective?: string | null
  status?: string | null
  budget_profile?: string | null
  policy?: Record<string, unknown>
  budget?: Record<string, unknown>
  budget_used?: Record<string, unknown>
  capabilities?: Array<Record<string, unknown>>
  skills?: Array<Record<string, unknown>>
  context_pack?: Record<string, unknown>
} & Record<string, unknown>)

export type ModelAdmissionV2VerifyRequest = {
  admission_package: Record<string, unknown>
  expected_bundle_sha256: string
  expected_environment: string
  expected_components?: Record<string, string>
  require_registered_active_admission?: true
}

export type ModelApprovalCreateRequest = {
  evidence_manifest_id: string
  approval_type: string
  decision: string
  reason: string
  expires_days?: number
  restrictions?: Array<string>
}

export type ModelEvidenceFreezeRequest = {
  deployment_bundle: Record<string, unknown>
}

export type ModelIntakeAdmissionRevokeRequest = {
  actor: string
  reason: string
}

export type ModelIntakeAdmissionVerifyRequest = {
  admission_package: Record<string, unknown>
  expected_artifact_sha256: string
  expected_repository_snapshot_sha256?: string | null
  require_registered_active_admission?: true
}

export type ModelIntakeAgentReplyRequest = {
  reply: string
}

export type ModelIntakeAgentSessionRequest = {
  objective: string
  max_iterations?: number
  action_budget?: number
}

export type ModelIntakeAutomaticReviewRequest = {
  source: string
  intended_environment?: string
  revision?: string | null
}

export type ModelIntakeReassessmentEventRequest = {
  trigger_type: string
  requested_action?: string
  actor: string
  reason: string
  artifact_sha256?: string | null
  statement_sha256?: string | null
  all_active?: boolean
  confirm_all_active?: boolean
  approval_receipt_id?: string | null
  evidence_digest?: string | null
  metadata_json?: Record<string, unknown>
}

export type ModelIntakeResolveRequest = {
  platform?: string
  ref: string
  revision?: string | null
  filename?: string | null
  metadata_json?: Record<string, unknown>
  timeout_seconds?: number
}

export type ModelIntakeRetentionCleanupRequest = {
  dry_run?: boolean
  retention_days?: number
  max_total_bytes?: number | null
  plan_sha256?: string | null
  confirm_delete?: boolean
  actor?: string | null
  reason?: string | null
  approval_receipt_id?: string | null
}

export type ModelIntakeScanRequest = {
  artifact_url: string
  name?: string | null
  intake_mode?: "admission" | "preflight"
  metadata_url?: string | null
  metadata_json?: Record<string, unknown>
  expected_sha256?: string | null
  signature_url?: string | null
  signature_public_key?: string | null
  signature_public_key_url?: string | null
  signature_value?: string | null
  signature_rsa_padding?: string | null
  signature_hash?: string | null
  signature_payload?: string | null
  signature_trusted_keys?: string | Array<string> | null
  signature_trusted_key_sha256?: string | Array<string> | null
  attestation_bundle_json?: Record<string, unknown> | null
  attestation_trusted_keys?: string | Array<string> | null
  attestation_trusted_key_sha256?: string | Array<string> | null
  allowed_attestation_predicate_types?: Array<string> | null
  required_attestation_builder_ids?: Array<string> | null
  require_attestation_verification?: boolean
  require_transparency_log?: boolean
  trust_anchor_ids?: Array<string> | null
  model_card_url?: string | null
  deployment_approved?: boolean
  require_deployment_approval?: boolean
  require_signature?: boolean
  require_signature_verification?: boolean
  require_cryptographic_signature_verification?: boolean
  require_hash?: boolean
  require_model_governance?: boolean
  policy_profile?: string | null
  policy_exceptions?: Array<Record<string, unknown>> | null
  max_download_bytes?: number
  complete_artifact_download?: boolean
  max_artifact_bytes?: number
  complete_repository_snapshot?: boolean
  max_repository_bytes?: number
  max_repository_files?: number
  run_generated_scanners?: boolean
  generated_scanner_names?: Array<string> | null
  run_dynamic_sandbox?: boolean
  require_dynamic_sandbox?: boolean
  require_current_workers?: boolean
  sandbox_timeout_seconds?: number
  evaluation_spec_json?: Record<string, unknown> | null
  run_generated_evaluation?: boolean
  require_generated_evaluation?: boolean
  require_signed_admission?: boolean
  admission_expires_days?: number
  admission_reassessment_days?: number
  timeout_seconds?: number
  allow_insecure_http?: boolean
  allow_private_networks?: boolean
  allowed_acquisition_hosts?: Array<string> | null
  allowed_acquisition_ports?: Array<number> | null
  max_acquisition_redirects?: number
  approval_receipt_id?: string | null
}

export type ModelIntakeTrustAnchorRequest = {
  name: string
  description?: string | null
  public_key_pem?: string | null
  public_key_sha256?: string | null
  policy_profile?: string | null
  purpose?: string
  environment?: string
  valid_from?: string | null
  valid_until?: string | null
  issuer_constraint?: string | null
  subject_constraint?: string | null
  builder_id_constraint?: string | null
  source?: string
  version?: string
  owner?: string | null
  is_active?: boolean
}

export type ModelLoaderProfileResolveRequest = {
  repository_manifest: Record<string, unknown>
  artifact_path: string
  runtime_image_digest: string
  reviewed_custom_code_sha256?: string | null
}

export type ModelPolicyDecisionCreateRequest = {
  evidence_manifest_id: string
}

export type ModelPromotionRequest = {
  policy_decision_id: string
  idempotency_key: string
}

export type ModelRunnerEvidenceReceiptRequest = {
  signature_envelope: Record<string, unknown>
}

export type ModelRunnerJobCreateRequest = {
  operation?: "calibration" | "runtime" | "conversion"
  deployment_bundle: Record<string, unknown>
  known_answer_inputs?: Array<string>
  known_answer_embedding_sha256?: string | null
  vcpu_count?: number
  memory_mib?: number
  timeout_seconds?: number
  output_bytes?: number | null
}

export type ModelRunnerStorageCleanupRequest = {
  dry_run?: boolean
  force_inactive_scratch?: boolean
}

export type ModelSubmissionRequest = {
  source: string
  source_kind?: string
  intended_environment: string
  intended_use?: Record<string, unknown>
  expected_artifact_sha256?: string | null
  publisher_signature?: Record<string, unknown> | null
  upstream_attestation?: Record<string, unknown> | null
  declared_metadata?: Record<string, unknown>
}

export type ModelSubmissionStaticRunRequest = {
  scan_id: string
}

export type RequestCollectionBindingUpsert = {
  target_kind: "web" | "api" | "device"
  target_id: string
  allowed_origins: Array<string>
  environment_id?: string | null
}

export type RequestCollectionCreate = {
  target_id: string
  name?: string | null
  format?: "auto" | "postman_collection" | "har" | "openapi"
  document: unknown
  environment?: unknown
  environment_name?: string | null
  base_url?: string | null
  import_limit?: number
  max_document_bytes?: number
}

export type RequestCollectionEnvironmentCreate = {
  name: string
  document: Record<string, unknown>
}

export type RequestCollectionSelect = {
  request_ids?: Array<string>
  folders?: Array<string>
  methods?: Array<string>
  path_regex?: string | null
  tags?: Array<string>
  safe_methods_only?: boolean
  limit?: number
}

export type RequestCollectionSelectionUpsert = {
  name: string
  binding_id: string
  replay_policy?: "discovery_only" | "safe_reads" | "safe_authentication" | "confirmed_active"
  request_ids?: Array<string>
  folders?: Array<string>
  methods?: Array<string>
  path_regex?: string | null
  tags?: Array<string>
  safe_methods_only?: boolean
  max_requests?: number
  disposable_credentials?: boolean
}

export type ScanFamilyPreviewRequest = {
  preset?: "passive" | "standard_active" | "custom"
  budget_profile?: "fast" | "balanced" | "thorough"
  include_families?: Array<string>
  exclude_families?: Array<string>
  active_testing?: boolean
  allow_state_changing_http?: boolean
  network_discovery?: boolean
  subdomain_discovery?: boolean
  execution_topology?: "single_worker" | "parallel"
}

export type ListCredentialProfilesCredentialProfilesGetRequest = never
export type ListCredentialProfilesCredentialProfilesGetResponse = unknown

export type CreateCredentialProfileCredentialProfilesPostRequest = CredentialProfileCreate
export type CreateCredentialProfileCredentialProfilesPostResponse = unknown

export type GetCredentialProfileCredentialProfilesProfileIdGetRequest = never
export type GetCredentialProfileCredentialProfilesProfileIdGetResponse = unknown

export type PatchCredentialProfileCredentialProfilesProfileIdPatchRequest = CredentialProfilePatch
export type PatchCredentialProfileCredentialProfilesProfileIdPatchResponse = unknown

export type DeleteCredentialProfileCredentialProfilesProfileIdDeleteRequest = never
export type DeleteCredentialProfileCredentialProfilesProfileIdDeleteResponse = unknown

export type RotateCredentialProfileCredentialProfilesProfileIdRotatePostRequest = CredentialProfileRotate
export type RotateCredentialProfileCredentialProfilesProfileIdRotatePostResponse = unknown

export type EvidenceExportBundleEvidenceExportBundleGetRequest = never
export type EvidenceExportBundleEvidenceExportBundleGetResponse = unknown

export type EvidenceExportManifestEvidenceExportManifestGetRequest = never
export type EvidenceExportManifestEvidenceExportManifestGetResponse = unknown

export type ListEvidenceInstancesEvidenceInstancesGetRequest = never
export type ListEvidenceInstancesEvidenceInstancesGetResponse = unknown

export type RecordEvidenceInstanceEvidenceInstancesPostRequest = EvidenceInstanceRequest
export type RecordEvidenceInstanceEvidenceInstancesPostResponse = unknown

export type GetEvidenceInstanceEvidenceInstancesInstanceIdGetRequest = never
export type GetEvidenceInstanceEvidenceInstancesInstanceIdGetResponse = unknown

export type ListEvidenceRetentionExecutionsEvidenceRetentionExecutionsGetRequest = never
export type ListEvidenceRetentionExecutionsEvidenceRetentionExecutionsGetResponse = unknown

export type EvidenceRetentionSweepEvidenceRetentionSweepPostRequest = EvidenceRetentionSweepRequest
export type EvidenceRetentionSweepEvidenceRetentionSweepPostResponse = unknown

export type GetEvidenceObjectEvidenceEvidenceIdGetRequest = never
export type GetEvidenceObjectEvidenceEvidenceIdGetResponse = unknown

export type ListHuntsHuntsGetRequest = never
export type ListHuntsHuntsGetResponse = unknown

export type StartHuntHuntsPostRequest = {
  schema_version?: "hunt-start/v2"
  target_id: string
  target_kind: "web" | "api" | "device" | "network"
  goal?: string | null
  objective?: string | null
  budget_profile?: "fast" | "balanced" | "thorough" | null
  policy_profile?: "fast" | "balanced" | "thorough" | null
  budgets?: Record<string, number>
  policy: {
    active_testing?: boolean
    allow_state_changing_http?: boolean
    network_discovery?: boolean
    allow_oob_interactions?: boolean
    allow_identity_headers?: boolean
    allow_direct_origin?: boolean
    authorization_confirmed?: boolean
    approval_receipt_id?: string | null
    scope_receipt_id?: string | null
  }
  credential_refs?: Record<string, string>
  capabilities?: Array<string>
  request_collection_ids?: Array<string>
  skill_ids?: Array<string>
  direct_origin_addresses?: Array<string>
  approval_receipt_id?: string | null
  scope_receipt_id?: string | null
}
export type StartHuntHuntsPostResponse = HuntStartV2Response

export type GetHuntContractHuntsContractGetRequest = never
export type GetHuntContractHuntsContractGetResponse = unknown

export type GetHuntLifecycleMetricsHuntsLifecycleMetricsGetRequest = never
export type GetHuntLifecycleMetricsHuntsLifecycleMetricsGetResponse = unknown

export type GetHuntHuntsHuntIdGetRequest = never
export type GetHuntHuntsHuntIdGetResponse = unknown

export type CancelHuntHuntsHuntIdCancelPostRequest = never
export type CancelHuntHuntsHuntIdCancelPostResponse = unknown

export type CreateHuntCandidateHuntsHuntIdCandidatesPostRequest = HuntCandidateRequest
export type CreateHuntCandidateHuntsHuntIdCandidatesPostResponse = unknown

export type VerifyHuntCandidateHuntsHuntIdCandidatesCandidateIdVerifyPostRequest = HuntCandidateVerifyRequest
export type VerifyHuntCandidateHuntsHuntIdCandidatesCandidateIdVerifyPostResponse = unknown

export type ExecuteHuntCapabilityHuntsHuntIdCapabilitiesCapabilityNamePostRequest = HuntCapabilityRequest
export type ExecuteHuntCapabilityHuntsHuntIdCapabilitiesCapabilityNamePostResponse = unknown

export type FinishHuntHuntsHuntIdFinishPostRequest = HuntFinishRequest
export type FinishHuntHuntsHuntIdFinishPostResponse = unknown

export type ExportHuntTransactionsHuntsHuntIdHttpTransactionsGetRequest = never
export type ExportHuntTransactionsHuntsHuntIdHttpTransactionsGetResponse = unknown

export type PurgeHuntTransactionsHuntsHuntIdHttpTransactionsDeleteRequest = never
export type PurgeHuntTransactionsHuntsHuntIdHttpTransactionsDeleteResponse = unknown

export type QueryHuntHuntsHuntIdQueryPostRequest = HuntQueryRequest
export type QueryHuntHuntsHuntIdQueryPostResponse = unknown

export type ExportHuntRecordHuntsHuntIdRecordGetRequest = never
export type ExportHuntRecordHuntsHuntIdRecordGetResponse = unknown

export type ResumeHuntHuntsHuntIdResumePostRequest = never
export type ResumeHuntHuntsHuntIdResumePostResponse = unknown

export type ConfirmHuntShellPlanHuntsHuntIdShellPlansPlanIdConfirmPostRequest = DeviceAgentShellConfirmRequest
export type ConfirmHuntShellPlanHuntsHuntIdShellPlansPlanIdConfirmPostResponse = unknown

export type VerifyModelIntakeAdmissionModelIntakeAdmissionVerifyPostRequest = ModelIntakeAdmissionVerifyRequest
export type VerifyModelIntakeAdmissionModelIntakeAdmissionVerifyPostResponse = unknown

export type ListModelIntakeAdmissionsModelIntakeAdmissionsGetRequest = never
export type ListModelIntakeAdmissionsModelIntakeAdmissionsGetResponse = unknown

export type ObserveModelIntakeDeploymentV2ModelIntakeAdmissionsV2ObservePostRequest = ModelAdmissionV2VerifyRequest
export type ObserveModelIntakeDeploymentV2ModelIntakeAdmissionsV2ObservePostResponse = unknown

export type VerifyModelIntakeAdmissionV2ModelIntakeAdmissionsV2VerifyPostRequest = ModelAdmissionV2VerifyRequest
export type VerifyModelIntakeAdmissionV2ModelIntakeAdmissionsV2VerifyPostResponse = unknown

export type GetModelIntakeAdmissionModelIntakeAdmissionsAdmissionIdGetRequest = never
export type GetModelIntakeAdmissionModelIntakeAdmissionsAdmissionIdGetResponse = unknown

export type RevokeModelIntakeAdmissionModelIntakeAdmissionsAdmissionIdRevokePostRequest = ModelIntakeAdmissionRevokeRequest
export type RevokeModelIntakeAdmissionModelIntakeAdmissionsAdmissionIdRevokePostResponse = unknown

export type GetModelIntakeAgentSessionModelIntakeAgentSessionSessionIdGetRequest = never
export type GetModelIntakeAgentSessionModelIntakeAgentSessionSessionIdGetResponse = unknown

export type CancelModelIntakeAgentSessionModelIntakeAgentSessionSessionIdCancelPostRequest = never
export type CancelModelIntakeAgentSessionModelIntakeAgentSessionSessionIdCancelPostResponse = unknown

export type ReplyModelIntakeAgentSessionModelIntakeAgentSessionSessionIdReplyPostRequest = ModelIntakeAgentReplyRequest
export type ReplyModelIntakeAgentSessionModelIntakeAgentSessionSessionIdReplyPostResponse = unknown

export type ListModelIntakeAutomaticReviewsModelIntakeAutomaticReviewsGetRequest = never
export type ListModelIntakeAutomaticReviewsModelIntakeAutomaticReviewsGetResponse = unknown

export type CreateModelIntakeAutomaticReviewModelIntakeAutomaticReviewsPostRequest = ModelIntakeAutomaticReviewRequest
export type CreateModelIntakeAutomaticReviewModelIntakeAutomaticReviewsPostResponse = unknown

export type GetModelIntakeAutomaticReviewModelIntakeAutomaticReviewsReviewIdGetRequest = never
export type GetModelIntakeAutomaticReviewModelIntakeAutomaticReviewsReviewIdGetResponse = unknown

export type GetModelIntakeAutomaticReviewReportModelIntakeAutomaticReviewsReviewIdReportGetRequest = never
export type GetModelIntakeAutomaticReviewReportModelIntakeAutomaticReviewsReviewIdReportGetResponse = unknown

export type ModelIntakeCapabilitiesModelIntakeCapabilitiesGetRequest = never
export type ModelIntakeCapabilitiesModelIntakeCapabilitiesGetResponse = unknown

export type ModelIntakeCheckCatalogModelIntakeChecksGetRequest = never
export type ModelIntakeCheckCatalogModelIntakeChecksGetResponse = unknown

export type ResolveModelIntakeConversionProfileModelIntakeConversionProfilesResolvePostRequest = ModelLoaderProfileResolveRequest
export type ResolveModelIntakeConversionProfileModelIntakeConversionProfilesResolvePostResponse = unknown

export type ResolveModelIntakeLoaderProfileModelIntakeLoaderProfilesResolvePostRequest = ModelLoaderProfileResolveRequest
export type ResolveModelIntakeLoaderProfileModelIntakeLoaderProfilesResolvePostResponse = unknown

export type ModelIntakeOperatorSessionModelIntakeOperatorSessionGetRequest = never
export type ModelIntakeOperatorSessionModelIntakeOperatorSessionGetResponse = unknown

export type ModelIntakeProviderReadinessModelIntakeProvidersReadinessGetRequest = never
export type ModelIntakeProviderReadinessModelIntakeProvidersReadinessGetResponse = unknown

export type CreateModelIntakeReassessmentEventModelIntakeReassessmentEventsPostRequest = ModelIntakeReassessmentEventRequest
export type CreateModelIntakeReassessmentEventModelIntakeReassessmentEventsPostResponse = unknown

export type ResolveModelIntakeModelIntakeResolvePostRequest = ModelIntakeResolveRequest
export type ResolveModelIntakeModelIntakeResolvePostResponse = unknown

export type CleanupModelIntakeQuarantineModelIntakeRetentionCleanupPostRequest = ModelIntakeRetentionCleanupRequest
export type CleanupModelIntakeQuarantineModelIntakeRetentionCleanupPostResponse = unknown

export type ModelIntakeRunnerInstallPlanModelIntakeRunnersInstallPlanGetRequest = never
export type ModelIntakeRunnerInstallPlanModelIntakeRunnersInstallPlanGetResponse = unknown

export type ModelIntakeRunnerReadinessModelIntakeRunnersReadinessGetRequest = never
export type ModelIntakeRunnerReadinessModelIntakeRunnersReadinessGetResponse = unknown

export type ModelIntakeRunnerStageStatusModelIntakeRunnersStageGetRequest = never
export type ModelIntakeRunnerStageStatusModelIntakeRunnersStageGetResponse = unknown

export type ModelIntakeRunnerStageModelIntakeRunnersStagePostRequest = never
export type ModelIntakeRunnerStageModelIntakeRunnersStagePostResponse = unknown

export type ModelIntakeRunnerStorageModelIntakeRunnersStorageGetRequest = never
export type ModelIntakeRunnerStorageModelIntakeRunnersStorageGetResponse = unknown

export type ModelIntakeRunnerStorageCleanupModelIntakeRunnersStorageCleanupPostRequest = ModelRunnerStorageCleanupRequest
export type ModelIntakeRunnerStorageCleanupModelIntakeRunnersStorageCleanupPostResponse = unknown

export type ScanModelIntakeModelIntakeScanPostRequest = ModelIntakeScanRequest
export type ScanModelIntakeModelIntakeScanPostResponse = unknown

export type ModelIntakeScannerReadinessModelIntakeScannersReadinessGetRequest = never
export type ModelIntakeScannerReadinessModelIntakeScannersReadinessGetResponse = unknown

export type GetModelIntakeEvidenceExportModelIntakeScansScanIdEvidenceExportGetRequest = never
export type GetModelIntakeEvidenceExportModelIntakeScansScanIdEvidenceExportGetResponse = unknown

export type DownloadModelIntakeLicenseBomModelIntakeScansScanIdLicenseBomGetRequest = never
export type DownloadModelIntakeLicenseBomModelIntakeScansScanIdLicenseBomGetResponse = unknown

export type DownloadModelIntakeSbomModelIntakeScansScanIdSbomGetRequest = never
export type DownloadModelIntakeSbomModelIntakeScansScanIdSbomGetResponse = unknown

export type ModelIntakeSbomSummaryModelIntakeScansScanIdSbomSummaryGetRequest = never
export type ModelIntakeSbomSummaryModelIntakeScansScanIdSbomSummaryGetResponse = unknown

export type DownloadModelIntakeThirdPartyNoticesModelIntakeScansScanIdThirdPartyNoticesGetRequest = never
export type DownloadModelIntakeThirdPartyNoticesModelIntakeScansScanIdThirdPartyNoticesGetResponse = unknown

export type ListModelIntakeSubmissionsModelIntakeSubmissionsGetRequest = never
export type ListModelIntakeSubmissionsModelIntakeSubmissionsGetResponse = unknown

export type CreateModelIntakeSubmissionModelIntakeSubmissionsPostRequest = ModelSubmissionRequest
export type CreateModelIntakeSubmissionModelIntakeSubmissionsPostResponse = unknown

export type GetModelIntakeSubmissionModelIntakeSubmissionsSubmissionIdGetRequest = never
export type GetModelIntakeSubmissionModelIntakeSubmissionsSubmissionIdGetResponse = unknown

export type CreateModelIntakeAgentSessionModelIntakeSubmissionsSubmissionIdAgentSessionPostRequest = ModelIntakeAgentSessionRequest
export type CreateModelIntakeAgentSessionModelIntakeSubmissionsSubmissionIdAgentSessionPostResponse = unknown

export type ListModelIntakeAgentSessionsModelIntakeSubmissionsSubmissionIdAgentSessionsGetRequest = never
export type ListModelIntakeAgentSessionsModelIntakeSubmissionsSubmissionIdAgentSessionsGetResponse = unknown

export type CreateModelIntakeApprovalModelIntakeSubmissionsSubmissionIdApprovalsPostRequest = ModelApprovalCreateRequest
export type CreateModelIntakeApprovalModelIntakeSubmissionsSubmissionIdApprovalsPostResponse = unknown

export type ModelIntakeEmbeddingConfigurationModelIntakeSubmissionsSubmissionIdEmbeddingConfigurationGetRequest = never
export type ModelIntakeEmbeddingConfigurationModelIntakeSubmissionsSubmissionIdEmbeddingConfigurationGetResponse = unknown

export type AttachModelIntakeRunnerEvidenceModelIntakeSubmissionsSubmissionIdEvidenceReceiptsPostRequest = ModelRunnerEvidenceReceiptRequest
export type AttachModelIntakeRunnerEvidenceModelIntakeSubmissionsSubmissionIdEvidenceReceiptsPostResponse = unknown

export type FreezeModelIntakeEvidenceModelIntakeSubmissionsSubmissionIdFreezeEvidencePostRequest = ModelEvidenceFreezeRequest
export type FreezeModelIntakeEvidenceModelIntakeSubmissionsSubmissionIdFreezeEvidencePostResponse = unknown

export type CreateModelIntakePolicyDecisionModelIntakeSubmissionsSubmissionIdPolicyDecisionsPostRequest = ModelPolicyDecisionCreateRequest
export type CreateModelIntakePolicyDecisionModelIntakeSubmissionsSubmissionIdPolicyDecisionsPostResponse = unknown

export type PromoteModelIntakeSubmissionModelIntakeSubmissionsSubmissionIdPromotePostRequest = ModelPromotionRequest
export type PromoteModelIntakeSubmissionModelIntakeSubmissionsSubmissionIdPromotePostResponse = unknown

export type GetModelIntakeSubmissionReportModelIntakeSubmissionsSubmissionIdReportGetRequest = never
export type GetModelIntakeSubmissionReportModelIntakeSubmissionsSubmissionIdReportGetResponse = unknown

export type ModelIntakeRunnerBundleModelIntakeSubmissionsSubmissionIdRunnerBundleGetRequest = never
export type ModelIntakeRunnerBundleModelIntakeSubmissionsSubmissionIdRunnerBundleGetResponse = unknown

export type ListModelIntakeRunnerJobsModelIntakeSubmissionsSubmissionIdRunnerJobsGetRequest = never
export type ListModelIntakeRunnerJobsModelIntakeSubmissionsSubmissionIdRunnerJobsGetResponse = unknown

export type CreateModelIntakeRunnerJobModelIntakeSubmissionsSubmissionIdRunnerJobsPostRequest = ModelRunnerJobCreateRequest
export type CreateModelIntakeRunnerJobModelIntakeSubmissionsSubmissionIdRunnerJobsPostResponse = unknown

export type RefreshModelIntakeRunnerJobModelIntakeSubmissionsSubmissionIdRunnerJobsJobIdRefreshPostRequest = never
export type RefreshModelIntakeRunnerJobModelIntakeSubmissionsSubmissionIdRunnerJobsJobIdRefreshPostResponse = unknown

export type AttachModelIntakeStaticRunModelIntakeSubmissionsSubmissionIdStaticRunsPostRequest = ModelSubmissionStaticRunRequest
export type AttachModelIntakeStaticRunModelIntakeSubmissionsSubmissionIdStaticRunsPostResponse = unknown

export type RescanModelIntakeTargetModelIntakeTargetsTargetIdRescanPostRequest = never
export type RescanModelIntakeTargetModelIntakeTargetsTargetIdRescanPostResponse = unknown

export type ListModelIntakeTrustAnchorsModelIntakeTrustAnchorsGetRequest = never
export type ListModelIntakeTrustAnchorsModelIntakeTrustAnchorsGetResponse = unknown

export type CreateModelIntakeTrustAnchorModelIntakeTrustAnchorsPostRequest = ModelIntakeTrustAnchorRequest
export type CreateModelIntakeTrustAnchorModelIntakeTrustAnchorsPostResponse = unknown

export type UpdateModelIntakeTrustAnchorModelIntakeTrustAnchorsAnchorIdPatchRequest = ModelIntakeTrustAnchorRequest
export type UpdateModelIntakeTrustAnchorModelIntakeTrustAnchorsAnchorIdPatchResponse = unknown

export type DeactivateModelIntakeTrustAnchorModelIntakeTrustAnchorsAnchorIdDeleteRequest = never
export type DeactivateModelIntakeTrustAnchorModelIntakeTrustAnchorsAnchorIdDeleteResponse = unknown

export type ListRequestCollectionsRequestCollectionsGetRequest = never
export type ListRequestCollectionsRequestCollectionsGetResponse = unknown

export type CreateRequestCollectionRequestCollectionsPostRequest = RequestCollectionCreate
export type CreateRequestCollectionRequestCollectionsPostResponse = unknown

export type GetRequestCollectionRequestCollectionsCollectionIdGetRequest = never
export type GetRequestCollectionRequestCollectionsCollectionIdGetResponse = unknown

export type UpsertRequestCollectionBindingRequestCollectionsCollectionIdBindingsPostRequest = RequestCollectionBindingUpsert
export type UpsertRequestCollectionBindingRequestCollectionsCollectionIdBindingsPostResponse = unknown

export type UpsertRequestCollectionEnvironmentRequestCollectionsCollectionIdEnvironmentsPostRequest = RequestCollectionEnvironmentCreate
export type UpsertRequestCollectionEnvironmentRequestCollectionsCollectionIdEnvironmentsPostResponse = unknown

export type DeactivateRequestCollectionEnvironmentRequestCollectionsCollectionIdEnvironmentsEnvironmentIdDeleteRequest = never
export type DeactivateRequestCollectionEnvironmentRequestCollectionsCollectionIdEnvironmentsEnvironmentIdDeleteResponse = unknown

export type ListRequestCollectionRequestsRequestCollectionsCollectionIdRequestsGetRequest = never
export type ListRequestCollectionRequestsRequestCollectionsCollectionIdRequestsGetResponse = unknown

export type SelectRequestCollectionIndexRequestCollectionsCollectionIdSelectPostRequest = RequestCollectionSelect
export type SelectRequestCollectionIndexRequestCollectionsCollectionIdSelectPostResponse = unknown

export type UpsertRequestCollectionSelectionRequestCollectionsCollectionIdSelectionsPostRequest = RequestCollectionSelectionUpsert
export type UpsertRequestCollectionSelectionRequestCollectionsCollectionIdSelectionsPostResponse = unknown

export type DeactivateRequestCollectionSelectionRequestCollectionsCollectionIdSelectionsSelectionIdDeleteRequest = never
export type DeactivateRequestCollectionSelectionRequestCollectionsCollectionIdSelectionsSelectionIdDeleteResponse = unknown

export type GetScanPublicContractScanContractsGetRequest = never
export type GetScanPublicContractScanContractsGetResponse = unknown

export type PreviewScanContractScanContractsPreviewPostRequest = ScanFamilyPreviewRequest
export type PreviewScanContractScanContractsPreviewPostResponse = unknown

export type ListScansScansGetRequest = never
export type ListScansScansGetResponse = unknown

export type SubmitScanScansPostRequest = {
  target: string
  name?: string | null
  target_kind?: "web" | "api"
  budget_profile?: "fast" | "balanced" | "thorough" | null
  policy?: Record<string, unknown> | null
  request_collections?: Array<Record<string, unknown>>
  credential_profile_ids?: Array<string>
  advanced?: {
    max_duration_seconds?: number | null
    max_http_requests?: number | null
    max_state_changing_requests?: number | null
    max_endpoints?: number | null
    max_hosts?: number | null
    max_browser_actions?: number | null
    max_tcp_ports?: number | null
    max_tool_wall_seconds?: number | null
    max_workers?: number | null
    include_families?: Array<string>
    exclude_families?: Array<string>
    force_single_worker?: boolean
  } | null
  approval_receipt_id?: string | null
  options?: {
    custom_endpoints?: Array<string>
    require_current_workers?: boolean
    placement?: {
      region?: string | null
      egress_group?: string | null
      network?: string | null
      budget_profile?: "fast" | "balanced" | "thorough" | null
      data_residency?: string | null
      node_id?: string | null
      node_scope?: "local" | "remote" | null
      requires?: Array<string>
    } | null
    parallel?: boolean | null
    shards?: number | "auto" | null
    shard_strategy?: "auto" | "scope" | "family" | "coverage" | "coverage_family" | null
    auth_state_shards?: boolean
  }
}
export type SubmitScanScansPostResponse = unknown

export type SubmitBatchScansBatchPostRequest = {
  targets: Array<string>
  target_kind?: "web" | "api"
  budget_profile?: "fast" | "balanced" | "thorough" | null
  policy?: Record<string, unknown> | null
  request_collections?: Array<Record<string, unknown>>
  credential_profile_ids?: Array<string>
  advanced?: {
    max_duration_seconds?: number | null
    max_http_requests?: number | null
    max_state_changing_requests?: number | null
    max_endpoints?: number | null
    max_hosts?: number | null
    max_browser_actions?: number | null
    max_tcp_ports?: number | null
    max_tool_wall_seconds?: number | null
    max_workers?: number | null
    include_families?: Array<string>
    exclude_families?: Array<string>
    force_single_worker?: boolean
  } | null
  approval_receipt_id?: string | null
  options?: {
    custom_endpoints?: Array<string>
    require_current_workers?: boolean
    placement?: {
      region?: string | null
      egress_group?: string | null
      network?: string | null
      budget_profile?: "fast" | "balanced" | "thorough" | null
      data_residency?: string | null
      node_id?: string | null
      node_scope?: "local" | "remote" | null
      requires?: Array<string>
    } | null
    parallel?: boolean | null
    shards?: number | "auto" | null
    shard_strategy?: "auto" | "scope" | "family" | "coverage" | "coverage_family" | null
    auth_state_shards?: boolean
  }
}
export type SubmitBatchScansBatchPostResponse = unknown

export type GetScanScansScanIdGetRequest = never
export type GetScanScansScanIdGetResponse = unknown

export type GetScanActionsScansScanIdActionsGetRequest = never
export type GetScanActionsScansScanIdActionsGetResponse = unknown

export type GetAiRedteamReportScansScanIdAiRedteamReportGetRequest = never
export type GetAiRedteamReportScansScanIdAiRedteamReportGetResponse = unknown

export type ListScanArtifactsScansScanIdArtifactsGetRequest = never
export type ListScanArtifactsScansScanIdArtifactsGetResponse = unknown

export type DownloadScanArtifactScansScanIdArtifactsArtifactIdGetRequest = never
export type DownloadScanArtifactScansScanIdArtifactsArtifactIdGetResponse = unknown

export type CancelScanScansScanIdCancelPostRequest = never
export type CancelScanScansScanIdCancelPostResponse = unknown

export type GetScanCapabilitiesScansScanIdCapabilitiesGetRequest = never
export type GetScanCapabilitiesScansScanIdCapabilitiesGetResponse = unknown

export type GetScanCoverageScansScanIdCoverageGetRequest = never
export type GetScanCoverageScansScanIdCoverageGetResponse = unknown

export type GetScanDeploymentDecisionScansScanIdDeploymentDecisionGetRequest = never
export type GetScanDeploymentDecisionScansScanIdDeploymentDecisionGetResponse = unknown

export type GetScanDeviceActivityScansScanIdDeviceActivityGetRequest = never
export type GetScanDeviceActivityScansScanIdDeviceActivityGetResponse = unknown

export type ExportScanTransactionsScansScanIdHttpTransactionsGetRequest = never
export type ExportScanTransactionsScansScanIdHttpTransactionsGetResponse = unknown

export type PurgeScanTransactionsScansScanIdHttpTransactionsDeleteRequest = never
export type PurgeScanTransactionsScansScanIdHttpTransactionsDeleteResponse = unknown

export type GetScanLogsScansScanIdLogsGetRequest = never
export type GetScanLogsScansScanIdLogsGetResponse = unknown

export type GetScanParityArtifactScansScanIdParityArtifactGetRequest = never
export type GetScanParityArtifactScansScanIdParityArtifactGetResponse = unknown

export type GetScanQueueDeliveryScansScanIdQueueDeliveryGetRequest = never
export type GetScanQueueDeliveryScansScanIdQueueDeliveryGetResponse = unknown

export type GetScanResultScansScanIdResultGetRequest = never
export type GetScanResultScansScanIdResultGetResponse = unknown

export interface PublicApiRequestByOperation {
  "list_credential_profiles_credential_profiles_get": ListCredentialProfilesCredentialProfilesGetRequest
  "create_credential_profile_credential_profiles_post": CreateCredentialProfileCredentialProfilesPostRequest
  "get_credential_profile_credential_profiles__profile_id__get": GetCredentialProfileCredentialProfilesProfileIdGetRequest
  "patch_credential_profile_credential_profiles__profile_id__patch": PatchCredentialProfileCredentialProfilesProfileIdPatchRequest
  "delete_credential_profile_credential_profiles__profile_id__delete": DeleteCredentialProfileCredentialProfilesProfileIdDeleteRequest
  "rotate_credential_profile_credential_profiles__profile_id__rotate_post": RotateCredentialProfileCredentialProfilesProfileIdRotatePostRequest
  "evidence_export_bundle_evidence_export_bundle_get": EvidenceExportBundleEvidenceExportBundleGetRequest
  "evidence_export_manifest_evidence_export_manifest_get": EvidenceExportManifestEvidenceExportManifestGetRequest
  "list_evidence_instances_evidence_instances_get": ListEvidenceInstancesEvidenceInstancesGetRequest
  "record_evidence_instance_evidence_instances_post": RecordEvidenceInstanceEvidenceInstancesPostRequest
  "get_evidence_instance_evidence_instances__instance_id__get": GetEvidenceInstanceEvidenceInstancesInstanceIdGetRequest
  "list_evidence_retention_executions_evidence_retention_executions_get": ListEvidenceRetentionExecutionsEvidenceRetentionExecutionsGetRequest
  "evidence_retention_sweep_evidence_retention_sweep_post": EvidenceRetentionSweepEvidenceRetentionSweepPostRequest
  "get_evidence_object_evidence__evidence_id__get": GetEvidenceObjectEvidenceEvidenceIdGetRequest
  "list_hunts_hunts_get": ListHuntsHuntsGetRequest
  "start_hunt_hunts_post": StartHuntHuntsPostRequest
  "get_hunt_contract_hunts_contract_get": GetHuntContractHuntsContractGetRequest
  "get_hunt_lifecycle_metrics_hunts_lifecycle_metrics_get": GetHuntLifecycleMetricsHuntsLifecycleMetricsGetRequest
  "get_hunt_hunts__hunt_id__get": GetHuntHuntsHuntIdGetRequest
  "cancel_hunt_hunts__hunt_id__cancel_post": CancelHuntHuntsHuntIdCancelPostRequest
  "create_hunt_candidate_hunts__hunt_id__candidates_post": CreateHuntCandidateHuntsHuntIdCandidatesPostRequest
  "verify_hunt_candidate_hunts__hunt_id__candidates__candidate_id__verify_post": VerifyHuntCandidateHuntsHuntIdCandidatesCandidateIdVerifyPostRequest
  "execute_hunt_capability_hunts__hunt_id__capabilities__capability_name__post": ExecuteHuntCapabilityHuntsHuntIdCapabilitiesCapabilityNamePostRequest
  "finish_hunt_hunts__hunt_id__finish_post": FinishHuntHuntsHuntIdFinishPostRequest
  "export_hunt_transactions_hunts__hunt_id__http_transactions_get": ExportHuntTransactionsHuntsHuntIdHttpTransactionsGetRequest
  "purge_hunt_transactions_hunts__hunt_id__http_transactions_delete": PurgeHuntTransactionsHuntsHuntIdHttpTransactionsDeleteRequest
  "query_hunt_hunts__hunt_id__query_post": QueryHuntHuntsHuntIdQueryPostRequest
  "export_hunt_record_hunts__hunt_id__record_get": ExportHuntRecordHuntsHuntIdRecordGetRequest
  "resume_hunt_hunts__hunt_id__resume_post": ResumeHuntHuntsHuntIdResumePostRequest
  "confirm_hunt_shell_plan_hunts__hunt_id__shell_plans__plan_id__confirm_post": ConfirmHuntShellPlanHuntsHuntIdShellPlansPlanIdConfirmPostRequest
  "verify_model_intake_admission_model_intake_admission_verify_post": VerifyModelIntakeAdmissionModelIntakeAdmissionVerifyPostRequest
  "list_model_intake_admissions_model_intake_admissions_get": ListModelIntakeAdmissionsModelIntakeAdmissionsGetRequest
  "observe_model_intake_deployment_v2_model_intake_admissions_v2_observe_post": ObserveModelIntakeDeploymentV2ModelIntakeAdmissionsV2ObservePostRequest
  "verify_model_intake_admission_v2_model_intake_admissions_v2_verify_post": VerifyModelIntakeAdmissionV2ModelIntakeAdmissionsV2VerifyPostRequest
  "get_model_intake_admission_model_intake_admissions__admission_id__get": GetModelIntakeAdmissionModelIntakeAdmissionsAdmissionIdGetRequest
  "revoke_model_intake_admission_model_intake_admissions__admission_id__revoke_post": RevokeModelIntakeAdmissionModelIntakeAdmissionsAdmissionIdRevokePostRequest
  "get_model_intake_agent_session_model_intake_agent_session__session_id__get": GetModelIntakeAgentSessionModelIntakeAgentSessionSessionIdGetRequest
  "cancel_model_intake_agent_session_model_intake_agent_session__session_id__cancel_post": CancelModelIntakeAgentSessionModelIntakeAgentSessionSessionIdCancelPostRequest
  "reply_model_intake_agent_session_model_intake_agent_session__session_id__reply_post": ReplyModelIntakeAgentSessionModelIntakeAgentSessionSessionIdReplyPostRequest
  "list_model_intake_automatic_reviews_model_intake_automatic_reviews_get": ListModelIntakeAutomaticReviewsModelIntakeAutomaticReviewsGetRequest
  "create_model_intake_automatic_review_model_intake_automatic_reviews_post": CreateModelIntakeAutomaticReviewModelIntakeAutomaticReviewsPostRequest
  "get_model_intake_automatic_review_model_intake_automatic_reviews__review_id__get": GetModelIntakeAutomaticReviewModelIntakeAutomaticReviewsReviewIdGetRequest
  "get_model_intake_automatic_review_report_model_intake_automatic_reviews__review_id__report_get": GetModelIntakeAutomaticReviewReportModelIntakeAutomaticReviewsReviewIdReportGetRequest
  "model_intake_capabilities_model_intake_capabilities_get": ModelIntakeCapabilitiesModelIntakeCapabilitiesGetRequest
  "model_intake_check_catalog_model_intake_checks_get": ModelIntakeCheckCatalogModelIntakeChecksGetRequest
  "resolve_model_intake_conversion_profile_model_intake_conversion_profiles_resolve_post": ResolveModelIntakeConversionProfileModelIntakeConversionProfilesResolvePostRequest
  "resolve_model_intake_loader_profile_model_intake_loader_profiles_resolve_post": ResolveModelIntakeLoaderProfileModelIntakeLoaderProfilesResolvePostRequest
  "model_intake_operator_session_model_intake_operator_session_get": ModelIntakeOperatorSessionModelIntakeOperatorSessionGetRequest
  "model_intake_provider_readiness_model_intake_providers_readiness_get": ModelIntakeProviderReadinessModelIntakeProvidersReadinessGetRequest
  "create_model_intake_reassessment_event_model_intake_reassessment_events_post": CreateModelIntakeReassessmentEventModelIntakeReassessmentEventsPostRequest
  "resolve_model_intake_model_intake_resolve_post": ResolveModelIntakeModelIntakeResolvePostRequest
  "cleanup_model_intake_quarantine_model_intake_retention_cleanup_post": CleanupModelIntakeQuarantineModelIntakeRetentionCleanupPostRequest
  "model_intake_runner_install_plan_model_intake_runners_install_plan_get": ModelIntakeRunnerInstallPlanModelIntakeRunnersInstallPlanGetRequest
  "model_intake_runner_readiness_model_intake_runners_readiness_get": ModelIntakeRunnerReadinessModelIntakeRunnersReadinessGetRequest
  "model_intake_runner_stage_status_model_intake_runners_stage_get": ModelIntakeRunnerStageStatusModelIntakeRunnersStageGetRequest
  "model_intake_runner_stage_model_intake_runners_stage_post": ModelIntakeRunnerStageModelIntakeRunnersStagePostRequest
  "model_intake_runner_storage_model_intake_runners_storage_get": ModelIntakeRunnerStorageModelIntakeRunnersStorageGetRequest
  "model_intake_runner_storage_cleanup_model_intake_runners_storage_cleanup_post": ModelIntakeRunnerStorageCleanupModelIntakeRunnersStorageCleanupPostRequest
  "scan_model_intake_model_intake_scan_post": ScanModelIntakeModelIntakeScanPostRequest
  "model_intake_scanner_readiness_model_intake_scanners_readiness_get": ModelIntakeScannerReadinessModelIntakeScannersReadinessGetRequest
  "get_model_intake_evidence_export_model_intake_scans__scan_id__evidence_export_get": GetModelIntakeEvidenceExportModelIntakeScansScanIdEvidenceExportGetRequest
  "download_model_intake_license_bom_model_intake_scans__scan_id__license_bom_get": DownloadModelIntakeLicenseBomModelIntakeScansScanIdLicenseBomGetRequest
  "download_model_intake_sbom_model_intake_scans__scan_id__sbom_get": DownloadModelIntakeSbomModelIntakeScansScanIdSbomGetRequest
  "model_intake_sbom_summary_model_intake_scans__scan_id__sbom_summary_get": ModelIntakeSbomSummaryModelIntakeScansScanIdSbomSummaryGetRequest
  "download_model_intake_third_party_notices_model_intake_scans__scan_id__third_party_notices_get": DownloadModelIntakeThirdPartyNoticesModelIntakeScansScanIdThirdPartyNoticesGetRequest
  "list_model_intake_submissions_model_intake_submissions_get": ListModelIntakeSubmissionsModelIntakeSubmissionsGetRequest
  "create_model_intake_submission_model_intake_submissions_post": CreateModelIntakeSubmissionModelIntakeSubmissionsPostRequest
  "get_model_intake_submission_model_intake_submissions__submission_id__get": GetModelIntakeSubmissionModelIntakeSubmissionsSubmissionIdGetRequest
  "create_model_intake_agent_session_model_intake_submissions__submission_id__agent_session_post": CreateModelIntakeAgentSessionModelIntakeSubmissionsSubmissionIdAgentSessionPostRequest
  "list_model_intake_agent_sessions_model_intake_submissions__submission_id__agent_sessions_get": ListModelIntakeAgentSessionsModelIntakeSubmissionsSubmissionIdAgentSessionsGetRequest
  "create_model_intake_approval_model_intake_submissions__submission_id__approvals_post": CreateModelIntakeApprovalModelIntakeSubmissionsSubmissionIdApprovalsPostRequest
  "model_intake_embedding_configuration_model_intake_submissions__submission_id__embedding_configuration_get": ModelIntakeEmbeddingConfigurationModelIntakeSubmissionsSubmissionIdEmbeddingConfigurationGetRequest
  "attach_model_intake_runner_evidence_model_intake_submissions__submission_id__evidence_receipts_post": AttachModelIntakeRunnerEvidenceModelIntakeSubmissionsSubmissionIdEvidenceReceiptsPostRequest
  "freeze_model_intake_evidence_model_intake_submissions__submission_id__freeze_evidence_post": FreezeModelIntakeEvidenceModelIntakeSubmissionsSubmissionIdFreezeEvidencePostRequest
  "create_model_intake_policy_decision_model_intake_submissions__submission_id__policy_decisions_post": CreateModelIntakePolicyDecisionModelIntakeSubmissionsSubmissionIdPolicyDecisionsPostRequest
  "promote_model_intake_submission_model_intake_submissions__submission_id__promote_post": PromoteModelIntakeSubmissionModelIntakeSubmissionsSubmissionIdPromotePostRequest
  "get_model_intake_submission_report_model_intake_submissions__submission_id__report_get": GetModelIntakeSubmissionReportModelIntakeSubmissionsSubmissionIdReportGetRequest
  "model_intake_runner_bundle_model_intake_submissions__submission_id__runner_bundle_get": ModelIntakeRunnerBundleModelIntakeSubmissionsSubmissionIdRunnerBundleGetRequest
  "list_model_intake_runner_jobs_model_intake_submissions__submission_id__runner_jobs_get": ListModelIntakeRunnerJobsModelIntakeSubmissionsSubmissionIdRunnerJobsGetRequest
  "create_model_intake_runner_job_model_intake_submissions__submission_id__runner_jobs_post": CreateModelIntakeRunnerJobModelIntakeSubmissionsSubmissionIdRunnerJobsPostRequest
  "refresh_model_intake_runner_job_model_intake_submissions__submission_id__runner_jobs__job_id__refresh_post": RefreshModelIntakeRunnerJobModelIntakeSubmissionsSubmissionIdRunnerJobsJobIdRefreshPostRequest
  "attach_model_intake_static_run_model_intake_submissions__submission_id__static_runs_post": AttachModelIntakeStaticRunModelIntakeSubmissionsSubmissionIdStaticRunsPostRequest
  "rescan_model_intake_target_model_intake_targets__target_id__rescan_post": RescanModelIntakeTargetModelIntakeTargetsTargetIdRescanPostRequest
  "list_model_intake_trust_anchors_model_intake_trust_anchors_get": ListModelIntakeTrustAnchorsModelIntakeTrustAnchorsGetRequest
  "create_model_intake_trust_anchor_model_intake_trust_anchors_post": CreateModelIntakeTrustAnchorModelIntakeTrustAnchorsPostRequest
  "update_model_intake_trust_anchor_model_intake_trust_anchors__anchor_id__patch": UpdateModelIntakeTrustAnchorModelIntakeTrustAnchorsAnchorIdPatchRequest
  "deactivate_model_intake_trust_anchor_model_intake_trust_anchors__anchor_id__delete": DeactivateModelIntakeTrustAnchorModelIntakeTrustAnchorsAnchorIdDeleteRequest
  "list_request_collections_request_collections_get": ListRequestCollectionsRequestCollectionsGetRequest
  "create_request_collection_request_collections_post": CreateRequestCollectionRequestCollectionsPostRequest
  "get_request_collection_request_collections__collection_id__get": GetRequestCollectionRequestCollectionsCollectionIdGetRequest
  "upsert_request_collection_binding_request_collections__collection_id__bindings_post": UpsertRequestCollectionBindingRequestCollectionsCollectionIdBindingsPostRequest
  "upsert_request_collection_environment_request_collections__collection_id__environments_post": UpsertRequestCollectionEnvironmentRequestCollectionsCollectionIdEnvironmentsPostRequest
  "deactivate_request_collection_environment_request_collections__collection_id__environments__environment_id__delete": DeactivateRequestCollectionEnvironmentRequestCollectionsCollectionIdEnvironmentsEnvironmentIdDeleteRequest
  "list_request_collection_requests_request_collections__collection_id__requests_get": ListRequestCollectionRequestsRequestCollectionsCollectionIdRequestsGetRequest
  "select_request_collection_index_request_collections__collection_id__select_post": SelectRequestCollectionIndexRequestCollectionsCollectionIdSelectPostRequest
  "upsert_request_collection_selection_request_collections__collection_id__selections_post": UpsertRequestCollectionSelectionRequestCollectionsCollectionIdSelectionsPostRequest
  "deactivate_request_collection_selection_request_collections__collection_id__selections__selection_id__delete": DeactivateRequestCollectionSelectionRequestCollectionsCollectionIdSelectionsSelectionIdDeleteRequest
  "get_scan_public_contract_scan_contracts_get": GetScanPublicContractScanContractsGetRequest
  "preview_scan_contract_scan_contracts_preview_post": PreviewScanContractScanContractsPreviewPostRequest
  "list_scans_scans_get": ListScansScansGetRequest
  "submit_scan_scans_post": SubmitScanScansPostRequest
  "submit_batch_scans_batch_post": SubmitBatchScansBatchPostRequest
  "get_scan_scans__scan_id__get": GetScanScansScanIdGetRequest
  "get_scan_actions_scans__scan_id__actions_get": GetScanActionsScansScanIdActionsGetRequest
  "get_ai_redteam_report_scans__scan_id__ai_redteam_report_get": GetAiRedteamReportScansScanIdAiRedteamReportGetRequest
  "list_scan_artifacts_scans__scan_id__artifacts_get": ListScanArtifactsScansScanIdArtifactsGetRequest
  "download_scan_artifact_scans__scan_id__artifacts__artifact_id__get": DownloadScanArtifactScansScanIdArtifactsArtifactIdGetRequest
  "cancel_scan_scans__scan_id__cancel_post": CancelScanScansScanIdCancelPostRequest
  "get_scan_capabilities_scans__scan_id__capabilities_get": GetScanCapabilitiesScansScanIdCapabilitiesGetRequest
  "get_scan_coverage_scans__scan_id__coverage_get": GetScanCoverageScansScanIdCoverageGetRequest
  "get_scan_deployment_decision_scans__scan_id__deployment_decision_get": GetScanDeploymentDecisionScansScanIdDeploymentDecisionGetRequest
  "get_scan_device_activity_scans__scan_id__device_activity_get": GetScanDeviceActivityScansScanIdDeviceActivityGetRequest
  "export_scan_transactions_scans__scan_id__http_transactions_get": ExportScanTransactionsScansScanIdHttpTransactionsGetRequest
  "purge_scan_transactions_scans__scan_id__http_transactions_delete": PurgeScanTransactionsScansScanIdHttpTransactionsDeleteRequest
  "get_scan_logs_scans__scan_id__logs_get": GetScanLogsScansScanIdLogsGetRequest
  "get_scan_parity_artifact_scans__scan_id__parity_artifact_get": GetScanParityArtifactScansScanIdParityArtifactGetRequest
  "get_scan_queue_delivery_scans__scan_id__queue_delivery_get": GetScanQueueDeliveryScansScanIdQueueDeliveryGetRequest
  "get_scan_result_scans__scan_id__result_get": GetScanResultScansScanIdResultGetRequest
}

export interface PublicApiResponseByOperation {
  "list_credential_profiles_credential_profiles_get": ListCredentialProfilesCredentialProfilesGetResponse
  "create_credential_profile_credential_profiles_post": CreateCredentialProfileCredentialProfilesPostResponse
  "get_credential_profile_credential_profiles__profile_id__get": GetCredentialProfileCredentialProfilesProfileIdGetResponse
  "patch_credential_profile_credential_profiles__profile_id__patch": PatchCredentialProfileCredentialProfilesProfileIdPatchResponse
  "delete_credential_profile_credential_profiles__profile_id__delete": DeleteCredentialProfileCredentialProfilesProfileIdDeleteResponse
  "rotate_credential_profile_credential_profiles__profile_id__rotate_post": RotateCredentialProfileCredentialProfilesProfileIdRotatePostResponse
  "evidence_export_bundle_evidence_export_bundle_get": EvidenceExportBundleEvidenceExportBundleGetResponse
  "evidence_export_manifest_evidence_export_manifest_get": EvidenceExportManifestEvidenceExportManifestGetResponse
  "list_evidence_instances_evidence_instances_get": ListEvidenceInstancesEvidenceInstancesGetResponse
  "record_evidence_instance_evidence_instances_post": RecordEvidenceInstanceEvidenceInstancesPostResponse
  "get_evidence_instance_evidence_instances__instance_id__get": GetEvidenceInstanceEvidenceInstancesInstanceIdGetResponse
  "list_evidence_retention_executions_evidence_retention_executions_get": ListEvidenceRetentionExecutionsEvidenceRetentionExecutionsGetResponse
  "evidence_retention_sweep_evidence_retention_sweep_post": EvidenceRetentionSweepEvidenceRetentionSweepPostResponse
  "get_evidence_object_evidence__evidence_id__get": GetEvidenceObjectEvidenceEvidenceIdGetResponse
  "list_hunts_hunts_get": ListHuntsHuntsGetResponse
  "start_hunt_hunts_post": StartHuntHuntsPostResponse
  "get_hunt_contract_hunts_contract_get": GetHuntContractHuntsContractGetResponse
  "get_hunt_lifecycle_metrics_hunts_lifecycle_metrics_get": GetHuntLifecycleMetricsHuntsLifecycleMetricsGetResponse
  "get_hunt_hunts__hunt_id__get": GetHuntHuntsHuntIdGetResponse
  "cancel_hunt_hunts__hunt_id__cancel_post": CancelHuntHuntsHuntIdCancelPostResponse
  "create_hunt_candidate_hunts__hunt_id__candidates_post": CreateHuntCandidateHuntsHuntIdCandidatesPostResponse
  "verify_hunt_candidate_hunts__hunt_id__candidates__candidate_id__verify_post": VerifyHuntCandidateHuntsHuntIdCandidatesCandidateIdVerifyPostResponse
  "execute_hunt_capability_hunts__hunt_id__capabilities__capability_name__post": ExecuteHuntCapabilityHuntsHuntIdCapabilitiesCapabilityNamePostResponse
  "finish_hunt_hunts__hunt_id__finish_post": FinishHuntHuntsHuntIdFinishPostResponse
  "export_hunt_transactions_hunts__hunt_id__http_transactions_get": ExportHuntTransactionsHuntsHuntIdHttpTransactionsGetResponse
  "purge_hunt_transactions_hunts__hunt_id__http_transactions_delete": PurgeHuntTransactionsHuntsHuntIdHttpTransactionsDeleteResponse
  "query_hunt_hunts__hunt_id__query_post": QueryHuntHuntsHuntIdQueryPostResponse
  "export_hunt_record_hunts__hunt_id__record_get": ExportHuntRecordHuntsHuntIdRecordGetResponse
  "resume_hunt_hunts__hunt_id__resume_post": ResumeHuntHuntsHuntIdResumePostResponse
  "confirm_hunt_shell_plan_hunts__hunt_id__shell_plans__plan_id__confirm_post": ConfirmHuntShellPlanHuntsHuntIdShellPlansPlanIdConfirmPostResponse
  "verify_model_intake_admission_model_intake_admission_verify_post": VerifyModelIntakeAdmissionModelIntakeAdmissionVerifyPostResponse
  "list_model_intake_admissions_model_intake_admissions_get": ListModelIntakeAdmissionsModelIntakeAdmissionsGetResponse
  "observe_model_intake_deployment_v2_model_intake_admissions_v2_observe_post": ObserveModelIntakeDeploymentV2ModelIntakeAdmissionsV2ObservePostResponse
  "verify_model_intake_admission_v2_model_intake_admissions_v2_verify_post": VerifyModelIntakeAdmissionV2ModelIntakeAdmissionsV2VerifyPostResponse
  "get_model_intake_admission_model_intake_admissions__admission_id__get": GetModelIntakeAdmissionModelIntakeAdmissionsAdmissionIdGetResponse
  "revoke_model_intake_admission_model_intake_admissions__admission_id__revoke_post": RevokeModelIntakeAdmissionModelIntakeAdmissionsAdmissionIdRevokePostResponse
  "get_model_intake_agent_session_model_intake_agent_session__session_id__get": GetModelIntakeAgentSessionModelIntakeAgentSessionSessionIdGetResponse
  "cancel_model_intake_agent_session_model_intake_agent_session__session_id__cancel_post": CancelModelIntakeAgentSessionModelIntakeAgentSessionSessionIdCancelPostResponse
  "reply_model_intake_agent_session_model_intake_agent_session__session_id__reply_post": ReplyModelIntakeAgentSessionModelIntakeAgentSessionSessionIdReplyPostResponse
  "list_model_intake_automatic_reviews_model_intake_automatic_reviews_get": ListModelIntakeAutomaticReviewsModelIntakeAutomaticReviewsGetResponse
  "create_model_intake_automatic_review_model_intake_automatic_reviews_post": CreateModelIntakeAutomaticReviewModelIntakeAutomaticReviewsPostResponse
  "get_model_intake_automatic_review_model_intake_automatic_reviews__review_id__get": GetModelIntakeAutomaticReviewModelIntakeAutomaticReviewsReviewIdGetResponse
  "get_model_intake_automatic_review_report_model_intake_automatic_reviews__review_id__report_get": GetModelIntakeAutomaticReviewReportModelIntakeAutomaticReviewsReviewIdReportGetResponse
  "model_intake_capabilities_model_intake_capabilities_get": ModelIntakeCapabilitiesModelIntakeCapabilitiesGetResponse
  "model_intake_check_catalog_model_intake_checks_get": ModelIntakeCheckCatalogModelIntakeChecksGetResponse
  "resolve_model_intake_conversion_profile_model_intake_conversion_profiles_resolve_post": ResolveModelIntakeConversionProfileModelIntakeConversionProfilesResolvePostResponse
  "resolve_model_intake_loader_profile_model_intake_loader_profiles_resolve_post": ResolveModelIntakeLoaderProfileModelIntakeLoaderProfilesResolvePostResponse
  "model_intake_operator_session_model_intake_operator_session_get": ModelIntakeOperatorSessionModelIntakeOperatorSessionGetResponse
  "model_intake_provider_readiness_model_intake_providers_readiness_get": ModelIntakeProviderReadinessModelIntakeProvidersReadinessGetResponse
  "create_model_intake_reassessment_event_model_intake_reassessment_events_post": CreateModelIntakeReassessmentEventModelIntakeReassessmentEventsPostResponse
  "resolve_model_intake_model_intake_resolve_post": ResolveModelIntakeModelIntakeResolvePostResponse
  "cleanup_model_intake_quarantine_model_intake_retention_cleanup_post": CleanupModelIntakeQuarantineModelIntakeRetentionCleanupPostResponse
  "model_intake_runner_install_plan_model_intake_runners_install_plan_get": ModelIntakeRunnerInstallPlanModelIntakeRunnersInstallPlanGetResponse
  "model_intake_runner_readiness_model_intake_runners_readiness_get": ModelIntakeRunnerReadinessModelIntakeRunnersReadinessGetResponse
  "model_intake_runner_stage_status_model_intake_runners_stage_get": ModelIntakeRunnerStageStatusModelIntakeRunnersStageGetResponse
  "model_intake_runner_stage_model_intake_runners_stage_post": ModelIntakeRunnerStageModelIntakeRunnersStagePostResponse
  "model_intake_runner_storage_model_intake_runners_storage_get": ModelIntakeRunnerStorageModelIntakeRunnersStorageGetResponse
  "model_intake_runner_storage_cleanup_model_intake_runners_storage_cleanup_post": ModelIntakeRunnerStorageCleanupModelIntakeRunnersStorageCleanupPostResponse
  "scan_model_intake_model_intake_scan_post": ScanModelIntakeModelIntakeScanPostResponse
  "model_intake_scanner_readiness_model_intake_scanners_readiness_get": ModelIntakeScannerReadinessModelIntakeScannersReadinessGetResponse
  "get_model_intake_evidence_export_model_intake_scans__scan_id__evidence_export_get": GetModelIntakeEvidenceExportModelIntakeScansScanIdEvidenceExportGetResponse
  "download_model_intake_license_bom_model_intake_scans__scan_id__license_bom_get": DownloadModelIntakeLicenseBomModelIntakeScansScanIdLicenseBomGetResponse
  "download_model_intake_sbom_model_intake_scans__scan_id__sbom_get": DownloadModelIntakeSbomModelIntakeScansScanIdSbomGetResponse
  "model_intake_sbom_summary_model_intake_scans__scan_id__sbom_summary_get": ModelIntakeSbomSummaryModelIntakeScansScanIdSbomSummaryGetResponse
  "download_model_intake_third_party_notices_model_intake_scans__scan_id__third_party_notices_get": DownloadModelIntakeThirdPartyNoticesModelIntakeScansScanIdThirdPartyNoticesGetResponse
  "list_model_intake_submissions_model_intake_submissions_get": ListModelIntakeSubmissionsModelIntakeSubmissionsGetResponse
  "create_model_intake_submission_model_intake_submissions_post": CreateModelIntakeSubmissionModelIntakeSubmissionsPostResponse
  "get_model_intake_submission_model_intake_submissions__submission_id__get": GetModelIntakeSubmissionModelIntakeSubmissionsSubmissionIdGetResponse
  "create_model_intake_agent_session_model_intake_submissions__submission_id__agent_session_post": CreateModelIntakeAgentSessionModelIntakeSubmissionsSubmissionIdAgentSessionPostResponse
  "list_model_intake_agent_sessions_model_intake_submissions__submission_id__agent_sessions_get": ListModelIntakeAgentSessionsModelIntakeSubmissionsSubmissionIdAgentSessionsGetResponse
  "create_model_intake_approval_model_intake_submissions__submission_id__approvals_post": CreateModelIntakeApprovalModelIntakeSubmissionsSubmissionIdApprovalsPostResponse
  "model_intake_embedding_configuration_model_intake_submissions__submission_id__embedding_configuration_get": ModelIntakeEmbeddingConfigurationModelIntakeSubmissionsSubmissionIdEmbeddingConfigurationGetResponse
  "attach_model_intake_runner_evidence_model_intake_submissions__submission_id__evidence_receipts_post": AttachModelIntakeRunnerEvidenceModelIntakeSubmissionsSubmissionIdEvidenceReceiptsPostResponse
  "freeze_model_intake_evidence_model_intake_submissions__submission_id__freeze_evidence_post": FreezeModelIntakeEvidenceModelIntakeSubmissionsSubmissionIdFreezeEvidencePostResponse
  "create_model_intake_policy_decision_model_intake_submissions__submission_id__policy_decisions_post": CreateModelIntakePolicyDecisionModelIntakeSubmissionsSubmissionIdPolicyDecisionsPostResponse
  "promote_model_intake_submission_model_intake_submissions__submission_id__promote_post": PromoteModelIntakeSubmissionModelIntakeSubmissionsSubmissionIdPromotePostResponse
  "get_model_intake_submission_report_model_intake_submissions__submission_id__report_get": GetModelIntakeSubmissionReportModelIntakeSubmissionsSubmissionIdReportGetResponse
  "model_intake_runner_bundle_model_intake_submissions__submission_id__runner_bundle_get": ModelIntakeRunnerBundleModelIntakeSubmissionsSubmissionIdRunnerBundleGetResponse
  "list_model_intake_runner_jobs_model_intake_submissions__submission_id__runner_jobs_get": ListModelIntakeRunnerJobsModelIntakeSubmissionsSubmissionIdRunnerJobsGetResponse
  "create_model_intake_runner_job_model_intake_submissions__submission_id__runner_jobs_post": CreateModelIntakeRunnerJobModelIntakeSubmissionsSubmissionIdRunnerJobsPostResponse
  "refresh_model_intake_runner_job_model_intake_submissions__submission_id__runner_jobs__job_id__refresh_post": RefreshModelIntakeRunnerJobModelIntakeSubmissionsSubmissionIdRunnerJobsJobIdRefreshPostResponse
  "attach_model_intake_static_run_model_intake_submissions__submission_id__static_runs_post": AttachModelIntakeStaticRunModelIntakeSubmissionsSubmissionIdStaticRunsPostResponse
  "rescan_model_intake_target_model_intake_targets__target_id__rescan_post": RescanModelIntakeTargetModelIntakeTargetsTargetIdRescanPostResponse
  "list_model_intake_trust_anchors_model_intake_trust_anchors_get": ListModelIntakeTrustAnchorsModelIntakeTrustAnchorsGetResponse
  "create_model_intake_trust_anchor_model_intake_trust_anchors_post": CreateModelIntakeTrustAnchorModelIntakeTrustAnchorsPostResponse
  "update_model_intake_trust_anchor_model_intake_trust_anchors__anchor_id__patch": UpdateModelIntakeTrustAnchorModelIntakeTrustAnchorsAnchorIdPatchResponse
  "deactivate_model_intake_trust_anchor_model_intake_trust_anchors__anchor_id__delete": DeactivateModelIntakeTrustAnchorModelIntakeTrustAnchorsAnchorIdDeleteResponse
  "list_request_collections_request_collections_get": ListRequestCollectionsRequestCollectionsGetResponse
  "create_request_collection_request_collections_post": CreateRequestCollectionRequestCollectionsPostResponse
  "get_request_collection_request_collections__collection_id__get": GetRequestCollectionRequestCollectionsCollectionIdGetResponse
  "upsert_request_collection_binding_request_collections__collection_id__bindings_post": UpsertRequestCollectionBindingRequestCollectionsCollectionIdBindingsPostResponse
  "upsert_request_collection_environment_request_collections__collection_id__environments_post": UpsertRequestCollectionEnvironmentRequestCollectionsCollectionIdEnvironmentsPostResponse
  "deactivate_request_collection_environment_request_collections__collection_id__environments__environment_id__delete": DeactivateRequestCollectionEnvironmentRequestCollectionsCollectionIdEnvironmentsEnvironmentIdDeleteResponse
  "list_request_collection_requests_request_collections__collection_id__requests_get": ListRequestCollectionRequestsRequestCollectionsCollectionIdRequestsGetResponse
  "select_request_collection_index_request_collections__collection_id__select_post": SelectRequestCollectionIndexRequestCollectionsCollectionIdSelectPostResponse
  "upsert_request_collection_selection_request_collections__collection_id__selections_post": UpsertRequestCollectionSelectionRequestCollectionsCollectionIdSelectionsPostResponse
  "deactivate_request_collection_selection_request_collections__collection_id__selections__selection_id__delete": DeactivateRequestCollectionSelectionRequestCollectionsCollectionIdSelectionsSelectionIdDeleteResponse
  "get_scan_public_contract_scan_contracts_get": GetScanPublicContractScanContractsGetResponse
  "preview_scan_contract_scan_contracts_preview_post": PreviewScanContractScanContractsPreviewPostResponse
  "list_scans_scans_get": ListScansScansGetResponse
  "submit_scan_scans_post": SubmitScanScansPostResponse
  "submit_batch_scans_batch_post": SubmitBatchScansBatchPostResponse
  "get_scan_scans__scan_id__get": GetScanScansScanIdGetResponse
  "get_scan_actions_scans__scan_id__actions_get": GetScanActionsScansScanIdActionsGetResponse
  "get_ai_redteam_report_scans__scan_id__ai_redteam_report_get": GetAiRedteamReportScansScanIdAiRedteamReportGetResponse
  "list_scan_artifacts_scans__scan_id__artifacts_get": ListScanArtifactsScansScanIdArtifactsGetResponse
  "download_scan_artifact_scans__scan_id__artifacts__artifact_id__get": DownloadScanArtifactScansScanIdArtifactsArtifactIdGetResponse
  "cancel_scan_scans__scan_id__cancel_post": CancelScanScansScanIdCancelPostResponse
  "get_scan_capabilities_scans__scan_id__capabilities_get": GetScanCapabilitiesScansScanIdCapabilitiesGetResponse
  "get_scan_coverage_scans__scan_id__coverage_get": GetScanCoverageScansScanIdCoverageGetResponse
  "get_scan_deployment_decision_scans__scan_id__deployment_decision_get": GetScanDeploymentDecisionScansScanIdDeploymentDecisionGetResponse
  "get_scan_device_activity_scans__scan_id__device_activity_get": GetScanDeviceActivityScansScanIdDeviceActivityGetResponse
  "export_scan_transactions_scans__scan_id__http_transactions_get": ExportScanTransactionsScansScanIdHttpTransactionsGetResponse
  "purge_scan_transactions_scans__scan_id__http_transactions_delete": PurgeScanTransactionsScansScanIdHttpTransactionsDeleteResponse
  "get_scan_logs_scans__scan_id__logs_get": GetScanLogsScansScanIdLogsGetResponse
  "get_scan_parity_artifact_scans__scan_id__parity_artifact_get": GetScanParityArtifactScansScanIdParityArtifactGetResponse
  "get_scan_queue_delivery_scans__scan_id__queue_delivery_get": GetScanQueueDeliveryScansScanIdQueueDeliveryGetResponse
  "get_scan_result_scans__scan_id__result_get": GetScanResultScansScanIdResultGetResponse
}

export type PublicApiOperationId = keyof typeof PUBLIC_API_OPERATIONS
