// Generated by scripts/generate_scan_contract.py. Do not edit by hand.

export const SCAN_PUBLIC_CONTRACT_SNAPSHOT = {
  "action_plan_schema": "scan-action-plan/v1",
  "advanced_limits": [
    {
      "maximum": 172800,
      "minimum": 1,
      "name": "max_duration_seconds",
      "profile_ceilings": {
        "balanced": 1200,
        "fast": 300,
        "thorough": 3600
      }
    },
    {
      "maximum": 1000000,
      "minimum": 1,
      "name": "max_http_requests",
      "profile_ceilings": {
        "balanced": 5000,
        "fast": 1000,
        "thorough": 20000
      }
    },
    {
      "maximum": 100000,
      "minimum": 1,
      "name": "max_endpoints",
      "profile_ceilings": {
        "balanced": 2000,
        "fast": 500,
        "thorough": 10000
      }
    },
    {
      "maximum": 20000,
      "minimum": 1,
      "name": "max_browser_actions",
      "profile_ceilings": {
        "balanced": 200,
        "fast": 50,
        "thorough": 1000
      }
    },
    {
      "maximum": 262140,
      "minimum": 1,
      "name": "max_tcp_ports",
      "profile_ceilings": {
        "balanced": 5000,
        "fast": 1000,
        "thorough": 20000
      }
    },
    {
      "maximum": 86400,
      "minimum": 1,
      "name": "max_tool_wall_seconds",
      "profile_ceilings": {
        "balanced": 900,
        "fast": 180,
        "thorough": 2700
      }
    },
    {
      "maximum": 128,
      "minimum": 1,
      "name": "max_workers",
      "profile_ceilings": {
        "balanced": 4,
        "fast": 2,
        "thorough": 8
      }
    },
    {
      "maximum": 100000,
      "minimum": 0,
      "name": "max_state_changing_requests",
      "profile_ceilings": {
        "balanced": 100,
        "fast": 20,
        "thorough": 500
      }
    },
    {
      "maximum": 100000,
      "minimum": 1,
      "name": "max_hosts",
      "profile_ceilings": {
        "balanced": 100,
        "fast": 25,
        "thorough": 500
      }
    }
  ],
  "budget_profiles": {
    "balanced": {
      "max_browser_actions": 200,
      "max_duration_seconds": 1200,
      "max_endpoints": 2000,
      "max_hosts": 100,
      "max_http_requests": 5000,
      "max_state_changing_requests": 100,
      "max_tcp_ports": 5000,
      "max_tool_wall_seconds": 900,
      "max_workers": 4
    },
    "fast": {
      "max_browser_actions": 50,
      "max_duration_seconds": 300,
      "max_endpoints": 500,
      "max_hosts": 25,
      "max_http_requests": 1000,
      "max_state_changing_requests": 20,
      "max_tcp_ports": 1000,
      "max_tool_wall_seconds": 180,
      "max_workers": 2
    },
    "thorough": {
      "max_browser_actions": 1000,
      "max_duration_seconds": 3600,
      "max_endpoints": 10000,
      "max_hosts": 500,
      "max_http_requests": 20000,
      "max_state_changing_requests": 500,
      "max_tcp_ports": 20000,
      "max_tool_wall_seconds": 2700,
      "max_workers": 8
    }
  },
  "credentials": {
    "interactive_auth_kinds": [
      "form_login",
      "oauth_client_credentials",
      "oauth_password"
    ],
    "secondary_auth_kinds": [
      "authorization_header",
      "basic_auth",
      "bearer_token",
      "cookie",
      "form_login"
    ],
    "semantic_capabilities": [
      "auth.session.establish",
      "authz.verify",
      "collections.replay_active",
      "collections.replay_authentication",
      "collections.replay_safe",
      "http.request",
      "sqli.request_verify",
      "sqli.request_verify_batch",
      "sqli.verify",
      "sqli.verify_batch",
      "templates.active_batch",
      "templates.passive_batch",
      "templates.passive_scan",
      "templates.scan",
      "web.content_discover",
      "web.crawl",
      "web.probe",
      "xss.request_verify",
      "xss.request_verify_batch",
      "xss.verify",
      "xss.verify_batch"
    ],
    "supported_auth_kinds": [
      "api_key_header",
      "authorization_header",
      "basic_auth",
      "bearer_token",
      "cookie",
      "custom_headers",
      "form_login",
      "oauth_client_credentials",
      "oauth_password"
    ]
  },
  "engine": "scan",
  "execution_plan_schema": "scan-execution-plan/v1",
  "families": [
    {
      "capabilities": [
        "web.probe",
        "web.crawl",
        "web.content_discover"
      ],
      "default_enabled": true,
      "description": "Crawl, API/HAR/OpenAPI discovery, and passive surface refresh.",
      "label": "Recon",
      "name": "recon",
      "requires_active_testing": false,
      "requires_credentials": false,
      "risk_level": "low"
    },
    {
      "capabilities": [
        "templates.passive_batch"
      ],
      "default_enabled": true,
      "description": "Reviewed read-only Nuclei templates included in passive Scan presets.",
      "label": "Nuclei (passive reviewed pack)",
      "name": "nuclei_passive",
      "requires_active_testing": false,
      "requires_credentials": false,
      "risk_level": "low"
    },
    {
      "capabilities": [
        "templates.active_batch"
      ],
      "default_enabled": false,
      "description": "Explicit active Nuclei templates, scheduled after deterministic verifier quotas.",
      "label": "Nuclei (active pack)",
      "name": "nuclei_active",
      "requires_active_testing": true,
      "requires_credentials": false,
      "risk_level": "medium"
    },
    {
      "capabilities": [
        "xss.verify_batch",
        "xss.request_verify_batch"
      ],
      "default_enabled": false,
      "description": "Reflected, stored, and DOM XSS probes.",
      "label": "Cross-site Scripting",
      "name": "xss",
      "requires_active_testing": true,
      "requires_credentials": false,
      "risk_level": "medium"
    },
    {
      "capabilities": [
        "sqli.verify_batch",
        "sqli.request_verify_batch"
      ],
      "default_enabled": false,
      "description": "SQL injection probes and proof/extraction depth.",
      "label": "SQL Injection",
      "name": "sqli",
      "requires_active_testing": true,
      "requires_credentials": false,
      "risk_level": "medium"
    },
    {
      "capabilities": [
        "authz.verify"
      ],
      "default_enabled": false,
      "description": "Multi-user object authorization comparisons. Requires Lab/deep policy and two auth contexts.",
      "label": "BOLA / IDOR",
      "name": "bola",
      "requires_active_testing": true,
      "requires_credentials": true,
      "risk_level": "high"
    }
  ],
  "family_presets": {
    "custom": [],
    "passive": [
      "recon",
      "nuclei_passive"
    ],
    "standard_active": [
      "recon",
      "nuclei_passive",
      "xss",
      "sqli"
    ]
  },
  "generation": "v2",
  "passive_coverage": {
    "baseline_capabilities": [
      "http.request",
      "dns.inspect",
      "tls.inspect"
    ],
    "default_families": [
      "recon",
      "nuclei_passive"
    ],
    "description": "Every passive Scan runs the target baseline, surface discovery, and the reviewed read-only template pack unless a family is excluded."
  },
  "request_collections": {
    "active_policy": "confirmed_active",
    "replay_policies": [
      "confirmed_active",
      "discovery_only",
      "safe_authentication",
      "safe_reads"
    ]
  },
  "schema_version": "scan-public-contract/v1"
} as const

export type ScanBudgetProfile = "fast" | "balanced" | "thorough"
export type ScanCredentialAuthKind = "api_key_header" | "authorization_header" | "basic_auth" | "bearer_token" | "cookie" | "custom_headers" | "form_login" | "oauth_client_credentials" | "oauth_password"
export type ScanReplayPolicy = "confirmed_active" | "discovery_only" | "safe_authentication" | "safe_reads"
export type ScanTargetKind = 'web' | 'api'

export type { SubmitScanScansPostRequest as ScanStartRequest } from './publicApi.generated'

export interface ScanPublicContract {
  schema_version: 'scan-public-contract/v1'
  generation: 'v2'
  engine: 'scan'
  execution_plan_schema: string
  action_plan_schema: string
  budget_profiles: Record<ScanBudgetProfile, Record<string, number>>
  advanced_limits: Array<{
    name: string
    minimum: number
    maximum: number
    profile_ceilings: Record<ScanBudgetProfile, number>
  }>
  families: Array<{
    name: string
    label: string
    description: string
    risk_level: string
    requires_active_testing: boolean
    requires_credentials: boolean
    default_enabled: boolean
    capabilities: string[]
  }>
  family_presets: Record<'passive' | 'standard_active' | 'custom', string[]>
  passive_coverage: {
    description: string
    baseline_capabilities: string[]
    default_families: string[]
  }
  credentials: {
    supported_auth_kinds: string[]
    interactive_auth_kinds: string[]
    secondary_auth_kinds: string[]
    semantic_capabilities: string[]
  }
  request_collections: {
    replay_policies: ScanReplayPolicy[]
    active_policy: 'confirmed_active'
  }
}
