import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const root = path.resolve(import.meta.dirname, '..')
const generated = fs.readFileSync(path.join(root, 'src/lib/huntContract.generated.ts'), 'utf8')
const client = fs.readFileSync(path.join(root, 'src/lib/huntV2.ts'), 'utf8')
const page = fs.readFileSync(path.join(root, 'src/app/hunt/page.tsx'), 'utf8')

test('Hunt UI consumes the generated server policy and zero-budget contract', () => {
  assert.match(generated, /Generated by scripts\/generate_hunt_contract\.py/)
  for (const dimension of [
    'max_active_actions',
    'max_browser_actions',
    'max_device_fragility_points',
    'max_hosts',
    'max_oob_interactions',
    'max_state_changing_requests',
    'max_tcp_ports',
    'max_udp_ports',
  ]) {
    assert.match(generated, new RegExp(`"${dimension}"`))
  }
  assert.match(client, /HUNT_START_CONTRACT\.schema_version/)
  assert.match(client, /allow_oob_interactions: request\.policy\.allowOobInteractions/)
  assert.match(page, /HUNT_BUDGET_DIMENSIONS\.filter\(\(item\) => item\.zeroable\)/)
  assert.match(page, /min="0"/)
  assert.match(page, /zero disables a dimension/)
})
