# Generated by scripts/generate_release_image_inventory.py; do not edit.
RELEASE_IMAGE_KEYS='scanner api ui signer model_intake'
RELEASE_IMAGE_LOCK_KEYS='SCANNER_IMAGE API_IMAGE UI_IMAGE SIGNER_IMAGE MODEL_INTAKE_IMAGE'
SCANNER_IMAGE_REPO_DEFAULT='shakerscan/shakerscan-scanner'
API_IMAGE_REPO_DEFAULT='shakerscan/shakerscan-api'
UI_IMAGE_REPO_DEFAULT='shakerscan/shakerscan-ui'
SIGNER_IMAGE_REPO_DEFAULT='shakerscan/shakerscan-model-intake-signer'
MODEL_INTAKE_IMAGE_REPO_DEFAULT='shakerscan/shakerscan-model-intake'
