#!/usr/bin/env python3
"""Generate the POSIX-shell projection of the canonical release image inventory."""

from __future__ import annotations

import argparse
from pathlib import Path

from release_image_inventory import RELEASE_IMAGES, ROOT

OUTPUT = ROOT / "install" / "release-images.sh"


def render() -> str:
    lines = [
        "# Generated by scripts/generate_release_image_inventory.py; do not edit.",
        "RELEASE_IMAGE_KEYS='" + " ".join(str(item["key"]) for item in RELEASE_IMAGES) + "'",
        "RELEASE_IMAGE_LOCK_KEYS='" + " ".join(str(item["lock_key"]) for item in RELEASE_IMAGES) + "'",
    ]
    lines.extend(
        f"{item['lock_key']}_REPO_DEFAULT='{item['repository']}'" for item in RELEASE_IMAGES
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("install/release-images.sh is stale")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
