#!/usr/bin/env python3
"""Generate the UI Hunt authority types from the canonical server contract."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "api"))

from hunt.start_contract import hunt_start_public_contract  # noqa: E402


OUTPUT = ROOT / "ui" / "src" / "lib" / "huntContract.generated.ts"


def render() -> str:
    contract = hunt_start_public_contract()
    zeroable = [
        item["name"] for item in contract["budget_dimensions"] if item["zeroable"]
    ]
    payload = json.dumps(contract, indent=2, sort_keys=True, ensure_ascii=False)
    zero_payload = json.dumps(zeroable, indent=2, ensure_ascii=False)
    return f"""// Generated by scripts/generate_hunt_contract.py. Do not edit by hand.

export const HUNT_START_CONTRACT = {payload} as const

export const HUNT_BUDGET_PROFILES = HUNT_START_CONTRACT.budget_profiles
export const HUNT_BUDGET_DIMENSIONS = HUNT_START_CONTRACT.budget_dimensions
export const HUNT_ZEROABLE_BUDGET_DIMENSIONS = {zero_payload} as const
export type HuntBudgetProfile = keyof typeof HUNT_BUDGET_PROFILES
export type HuntBudgetDimension = typeof HUNT_BUDGET_DIMENSIONS[number]['name']
export type HuntZeroableBudgetDimension = typeof HUNT_ZEROABLE_BUDGET_DIMENSIONS[number]
export type HuntTargetKind = typeof HUNT_START_CONTRACT.target_kinds[number]
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"out of date: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"updated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
