#!/usr/bin/env python3
"""Generate UI Scan request/contract types from the canonical server contract."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
# The repo root lets `scanner.redaction` (the source-layout fallback inside
# api/runtime/receipts.py) resolve; api/ lets `scan.contracts` resolve. Without
# the root, this script only works in the flat container layout, so a bare CI
# runner fails with "No module named 'scanner'".
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "api"))

from scan.contracts import public_scan_contract  # noqa: E402


OUTPUT = ROOT / "ui" / "src" / "lib" / "scanContract.generated.ts"


def _union(values: Iterable[str]) -> str:
    return " | ".join(json.dumps(str(value)) for value in values)


def render() -> str:
    contract = public_scan_contract()
    payload = json.dumps(contract, indent=2, sort_keys=True, ensure_ascii=False)
    budget_profiles = _union(contract["budget_profiles"])
    auth_kinds = _union(contract["credentials"]["supported_auth_kinds"])
    replay_policies = _union(contract["request_collections"]["replay_policies"])
    return f"""// Generated by scripts/generate_scan_contract.py. Do not edit by hand.

export const SCAN_PUBLIC_CONTRACT_SNAPSHOT = {payload} as const

export type ScanBudgetProfile = {budget_profiles}
export type ScanCredentialAuthKind = {auth_kinds}
export type ScanReplayPolicy = {replay_policies}
export type ScanTargetKind = 'web' | 'api'

export type {{ SubmitScanScansPostRequest as ScanStartRequest }} from './publicApi.generated'

export interface ScanPublicContract {{
  schema_version: 'scan-public-contract/v1'
  generation: 'v2'
  engine: 'scan'
  execution_plan_schema: string
  action_plan_schema: string
  budget_profiles: Record<ScanBudgetProfile, Record<string, number>>
  advanced_limits: Array<{{
    name: string
    minimum: number
    maximum: number
    profile_ceilings: Record<ScanBudgetProfile, number>
  }}>
  families: Array<{{
    name: string
    label: string
    description: string
    risk_level: string
    requires_active_testing: boolean
    requires_credentials: boolean
    default_enabled: boolean
    capabilities: string[]
  }}>
  family_presets: Record<'passive' | 'standard_active' | 'custom', string[]>
  passive_coverage: {{
    description: string
    baseline_capabilities: string[]
    default_families: string[]
  }}
  credentials: {{
    supported_auth_kinds: string[]
    interactive_auth_kinds: string[]
    secondary_auth_kinds: string[]
    semantic_capabilities: string[]
  }}
  request_collections: {{
    replay_policies: ScanReplayPolicy[]
    active_policy: 'confirmed_active'
  }}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"out of date: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"updated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
