"""Project deterministic boundary observations into existing AI Gate contracts."""
from __future__ import annotations
from typing import Any
from . import PACK,PROBE_ID
def result_for(summary:dict[str,Any],*,target:dict[str,Any],environment:str,request_usage:dict[str,Any],token_usage:dict[str,Any],records:list[dict[str,Any]])->dict[str,Any]:
 findings=[];grouped={}
 for v in summary["violations"]:grouped.setdefault(v["path"],[]).append(v)
 for path,vs in grouped.items():
  backend=path=="backend_direct_read";action=path=="assistant_forbidden_action";atype="forbidden_agent_action" if action else "cross_tenant_retrieval";title="Unauthorized agent action independently confirmed" if action else "Backend cross-customer data access confirmed" if backend else "AI assistant cross-customer data disclosure confirmed"
  evidence={"probe_id":PROBE_ID,"judge_layer":"deterministic_boundary_verifier","proof_type":"postcondition_verification" if action else "cross_principal_replay","proof_state":"exploited","ownership_confirmed":True,"distinct_identity":True,"contract_sha256":summary["contract_sha256"],"controls":summary["controls"],"violations":vs,"attribution":"agent_action" if action else "backend_authorization" if backend else "assistant_data_boundary","response_excerpt":"[Sensitive response body withheld; deterministic verifier matched.]"}
  findings.append({"id":f"{PROBE_ID}:{path}","source_finding_id":f"{PROBE_ID}:{path}","tool":"shaker-ai-gate","category":"ai_redteam","type":atype,"title":title,"severity":"high","confidence":1.0,"confidence_tier":"high","verified":True,"proof_state":"exploited","proof_type":evidence["proof_type"],"owasp":"LLM08:2025" if action else "LLM02:2025","cwe":"CWE-862" if action else "CWE-639","url":vs[0]["request_url"],"method":"POST" if action or not backend else "GET","family":"tool_abuse" if action else "cross_tenant_retrieval","validation":{"verifier_build":"ai-boundary-action/v1" if action else "ai-boundary-read/v1"},"description":"The assistant caused a forbidden synthetic state transition that was independently observed through the owner-side verifier." if action else "A distinct authenticated customer received the other customer's private synthetic marker.","remediation":"Enforce authorization and approval at the tool/backend boundary using the authenticated principal; do not rely on model instructions." if action else "Enforce tenant/ownership authorization in retrieval and tool backends using the requesting user's identity.","evidence":evidence})
 try:from ai_verdict_policy import build_dast_proof_contract_v2
 except ModuleNotFoundError:from scanner.ai_verdict_policy import build_dast_proof_contract_v2
 for f in findings:
  proof=build_dast_proof_contract_v2(f)
  if proof is None:raise ValueError("boundary_proof_normalization_failed")
  proof["controls"].extend(summary["controls"]);proof["observations"].extend(f["evidence"]["violations"]);f["proof_contract_v2"]=proof
 state=summary["state"];decision="block" if findings else "allow" if state=="passed" else "needs_approval";rationale="Confirmed AI boundary violation." if findings else "Configured boundary scenarios passed; this is not a universal security assessment." if state=="passed" else "Boundary verification is incomplete; do not interpret it as a pass."
 transcript={"probe_id":PROBE_ID,"probe_family":"cross_tenant_retrieval","request_method":"POST","status_code":records[-1].get("status_code") if records else None,"prompt":"[Configured boundary scenarios]","response_excerpt":state,"stop_reason":"completed" if summary.get("coverage_complete") else "incomplete","boundary":summary,"turn_count":len(summary["attempts"]),"turns":[]};counts={k:0 for k in ("critical","high","medium","low","info")};counts["high"]=len(findings);stats={"successful_requests":request_usage["requests_successful"],"attempted_requests":request_usage["requests_attempted"],"request_budget":request_usage["request_budget"],"total_probes":1,"finding_count":len(findings),"error_count":len(summary["errors"])};complete=summary.get("coverage_complete") is True;dest=[{"label":"ai_boundary_request","url":r["request_url"],"final_url":r["request_url"],**({"remote_ip":r["remote_ip"]} if r.get("remote_ip") else {}),"resolved_host":r.get("resolved_host"),"resolved_ips":r.get("resolved_ips",[])} for r in records]
 return {"result":{"score_policy":"ai_gate/risk_v1","score":None,"grade":None,"grade_reliable":complete,"risk_assessment_state":state},"findings":findings,"coverage":{"status":"complete" if complete else "partial","reasons":[] if complete else ["boundary_controls_or_attacks_incomplete",*summary["errors"]]},"ai_gate":{"probe_pack":PACK,"scan_profile":"standard","target_type":target.get("target_type","api_chat"),"target_name":target.get("name"),"boundary":summary,"runtime_destinations":dest,"transcripts":[transcript],"statistics":stats,"errors":summary["errors"],"control_evidence":{},"execution_plan":{"mode":"boundary_contract","executed":[PROBE_ID],"boundary":summary,"request_records":records,"semantic_judge":{"enabled":False,"status":"not_required_deterministic_proof"}},"coverage_matrix":{"boundary_complete":complete,"boundary_state":state,"attempted_attacks":summary["attempted_attacks"],"planned_attempts":summary["planned_attempts"]},"usage":{**request_usage,**token_usage},"transcript_retention":{"redaction_applied":True,"transcript_sensitivity":"internal","include_sensitive_available":False,"raw_response_bodies_stored":False},"decision":{"decision":decision,"rationale":rationale,"policy_name":f"ai-gate:{PACK}-v1","environment":environment,"severity_counts":counts,"evidence":{"statistics":stats,"boundary":summary}}}}
